In [24]:
import numpy as np
import pandas as pd

In [25]:
# loading data
genotype = pd.read_csv("../processed/africa_geno.csv")

In [26]:
genotype.info()

<class 'pandas.DataFrame'>
RangeIndex: 20951 entries, 0 to 20950
Data columns (total 55 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  20951 non-null  int64
 1   Sample                      14508 non-null  str
 2   crt_72[C]                   14508 non-null  str
 3   crt_74[M]                   14508 non-null  str
 4   crt_75[N]                   14508 non-null  str
 5   crt_76[K]                   14508 non-null  str
 6   crt_72-76[CVMNK]            14508 non-null  str
 7   crt_93[T]                   14508 non-null  str
 8   crt_97[H]                   14508 non-null  str
 9   crt_218[I]                  14508 non-null  str
 10  crt_220[A]                  14508 non-null  str
 11  crt_271[Q]                  14508 non-null  str
 12  crt_326[N]                  14508 non-null  str
 13  crt_333[T]                  14508 non-null  str
 14  crt_353[G]                  14508 non-null  str
 15  crt_356[I]                  14508 non-null  str
 16  crt_371[R]                  14508 non-null  str
 17  dhfr_16[N]                  14508 non-null  str
 18  dhfr_51[N]                  14508 non-null  str
 19  dhfr_59[C]                  14508 non-null  str
 20  dhfr_108[S]                 14508 non-null  str
 21  dhfr_164[I]                 14508 non-null  str
 22  dhfr_306[S]                 14508 non-null  str
 23  dhps_436[S]                 14508 non-null  str
 24  dhps_437[G]                 14508 non-null  str
 25  dhps_540[K]                 14508 non-null  str
 26  dhps_581[A]                 14508 non-null  str
 27  dhps_613[A]                 14508 non-null  str
 28  exo_415[E]                  14508 non-null  str
 29  mdr1_86[N]                  14508 non-null  str
 30  mdr1_184[Y]                 14508 non-null  str
 31  mdr1_1034[S]                14508 non-null  str
 32  mdr1_1042[N]                14508 non-null  str
 33  mdr1_1226[F]                14508 non-null  str
 34  mdr1_1246[D]                14508 non-null  str
 35  arps10_127-128[VD]          14508 non-null  str
 36  fd_193[D]                   14508 non-null  str
 37  mdr2_484[T]                 14508 non-null  str
 38  kelch13_349-726_ns_changes  14508 non-null  str
 39  mdr1_dup_call               14508 non-null  str
 40  pm2_dup_call                14508 non-null  str
 41  sample_id                   20951 non-null  str
 42  year                        20951 non-null  int64
 43  qc_pass                     20951 non-null  bool
 44  study_id                    20951 non-null  int64
 45  country                     20951 non-null  str
 46  country_id                  20951 non-null  str
 47  site                        20951 non-null  str
 48  site_id                     20951 non-null  str
 49  ARTresistant                14508 non-null  str
 50  CQresistant                 14508 non-null  str
 51  MQresistant                 14508 non-null  str
 52  PPQresistant                14508 non-null  str
 53  PYRresistant                14508 non-null  str
 54  SDXresistant                14508 non-null  str
dtypes: bool(1), int64(3), str(51)
memory usage: 8.7 MB

In [27]:
# null count
genotype.isna().sum()

Unnamed: 0                       0
Sample                        6443
crt_72[C]                     6443
crt_74[M]                     6443
crt_75[N]                     6443
crt_76[K]                     6443
crt_72-76[CVMNK]              6443
crt_93[T]                     6443
crt_97[H]                     6443
crt_218[I]                    6443
crt_220[A]                    6443
crt_271[Q]                    6443
crt_326[N]                    6443
crt_333[T]                    6443
crt_353[G]                    6443
crt_356[I]                    6443
crt_371[R]                    6443
dhfr_16[N]                    6443
dhfr_51[N]                    6443
dhfr_59[C]                    6443
dhfr_108[S]                   6443
dhfr_164[I]                   6443
dhfr_306[S]                   6443
dhps_436[S]                   6443
dhps_437[G]                   6443
dhps_540[K]                   6443
dhps_581[A]                   6443
dhps_613[A]                   6443
exo_415[E]                    6443
mdr1_86[N]                    6443
mdr1_184[Y]                   6443
mdr1_1034[S]                  6443
mdr1_1042[N]                  6443
mdr1_1226[F]                  6443
mdr1_1246[D]                  6443
arps10_127-128[VD]            6443
fd_193[D]                     6443
mdr2_484[T]                   6443
kelch13_349-726_ns_changes    6443
mdr1_dup_call                 6443
pm2_dup_call                  6443
sample_id                        0
year                             0
qc_pass                          0
study_id                         0
country                          0
country_id                       0
site                             0
site_id                          0
ARTresistant                  6443
CQresistant                   6443
MQresistant                   6443
PPQresistant                  6443
PYRresistant                  6443
SDXresistant                  6443
dtype: int64

In [28]:
genotype.shape

(20951, 55)

In [29]:
# determine if the missing data is from identical samples
# lack phenotypic data
cols = [
    "ARTresistant",
    "CQresistant",
    "MQresistant",
    "PPQresistant",
    "PYRresistant",
    "SDXresistant"
]

all(
    genotype[cols[0]].isna().equals(genotype[col].isna())
    for col in cols[1:])

True

In [30]:
# drop all rows with no phenotypic data
genotype.dropna(subset= cols , how='all', inplace= True)

In [31]:
#confirming drop
genotype[cols].isna().sum()

ARTresistant    0
CQresistant     0
MQresistant     0
PPQresistant    0
PYRresistant    0
SDXresistant    0
dtype: int64

In [32]:
genotype.isna().sum()

Unnamed: 0                    0
Sample                        0
crt_72[C]                     0
crt_74[M]                     0
crt_75[N]                     0
crt_76[K]                     0
crt_72-76[CVMNK]              0
crt_93[T]                     0
crt_97[H]                     0
crt_218[I]                    0
crt_220[A]                    0
crt_271[Q]                    0
crt_326[N]                    0
crt_333[T]                    0
crt_353[G]                    0
crt_356[I]                    0
crt_371[R]                    0
dhfr_16[N]                    0
dhfr_51[N]                    0
dhfr_59[C]                    0
dhfr_108[S]                   0
dhfr_164[I]                   0
dhfr_306[S]                   0
dhps_436[S]                   0
dhps_437[G]                   0
dhps_540[K]                   0
dhps_581[A]                   0
dhps_613[A]                   0
exo_415[E]                    0
mdr1_86[N]                    0
mdr1_184[Y]                   0
mdr1_1034[S]                  0
mdr1_1042[N]                  0
mdr1_1226[F]                  0
mdr1_1246[D]                  0
arps10_127-128[VD]            0
fd_193[D]                     0
mdr2_484[T]                   0
kelch13_349-726_ns_changes    0
mdr1_dup_call                 0
pm2_dup_call                  0
sample_id                     0
year                          0
qc_pass                       0
study_id                      0
country                       0
country_id                    0
site                          0
site_id                       0
ARTresistant                  0
CQresistant                   0
MQresistant                   0
PPQresistant                  0
PYRresistant                  0
SDXresistant                  0
dtype: int64

### dropping unnecessary columns

In [33]:
# viewing the data
genotype.head()

,Unnamed: 0,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],...,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,0,FP0008-C,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,1,FP0009-C,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,2,FP0010-CW,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,3,FP0011-CW,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,4,FP0012-CW,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [34]:
genotype.columns

Index(['Unnamed: 0', 'Sample', 'crt_72[C]', 'crt_74[M]', 'crt_75[N]',
       'crt_76[K]', 'crt_72-76[CVMNK]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]',
       'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]',
       'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]',
       'dhfr_108[S]', 'dhfr_164[I]', 'dhfr_306[S]', 'dhps_436[S]',
       'dhps_437[G]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]',
       'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]',
       'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]',
       'fd_193[D]', 'mdr2_484[T]', 'kelch13_349-726_ns_changes',
       'mdr1_dup_call', 'pm2_dup_call', 'sample_id', 'year', 'qc_pass',
       'study_id', 'country', 'country_id', 'site', 'site_id', 'ARTresistant',
       'CQresistant', 'MQresistant', 'PPQresistant', 'PYRresistant',
       'SDXresistant'],
      dtype='str')

In [35]:
# dropping columns not used in the model
cols_del = ['year', 'qc_pass','study_id', 'country', 'country_id', 'site', 'site_id','Unnamed: 0','Sample','sample_id']
genotype.drop(columns = cols_del, inplace = True)

In [36]:
genotype.columns

Index(['crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]', 'crt_72-76[CVMNK]',
       'crt_93[T]', 'crt_97[H]', 'crt_218[I]', 'crt_220[A]', 'crt_271[Q]',
       'crt_326[N]', 'crt_333[T]', 'crt_353[G]', 'crt_356[I]', 'crt_371[R]',
       'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]', 'dhfr_108[S]', 'dhfr_164[I]',
       'dhfr_306[S]', 'dhps_436[S]', 'dhps_437[G]', 'dhps_540[K]',
       'dhps_581[A]', 'dhps_613[A]', 'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]',
       'mdr1_1034[S]', 'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]',
       'arps10_127-128[VD]', 'fd_193[D]', 'mdr2_484[T]',
       'kelch13_349-726_ns_changes', 'mdr1_dup_call', 'pm2_dup_call',
       'ARTresistant', 'CQresistant', 'MQresistant', 'PPQresistant',
       'PYRresistant', 'SDXresistant'],
      dtype='str')

In [37]:
genotype.head()

,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],crt_271[Q],...,mdr2_484[T],kelch13_349-726_ns_changes,mdr1_dup_call,pm2_dup_call,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,...,Sensitive,Missing,Sensitive,Sensitive,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Resistant,Resistant,...,Sensitive,Missing,Sensitive,Sensitive,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Missing,Sensitive,Sensitive,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Missing,Sensitive,Sensitive,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Resistant,Resistant,...,Sensitive,Missing,Sensitive,Sensitive,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [38]:
genotype.info()

<class 'pandas.DataFrame'>
Index: 14508 entries, 0 to 20950
Data columns (total 45 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   crt_72[C]                   14508 non-null  str
 1   crt_74[M]                   14508 non-null  str
 2   crt_75[N]                   14508 non-null  str
 3   crt_76[K]                   14508 non-null  str
 4   crt_72-76[CVMNK]            14508 non-null  str
 5   crt_93[T]                   14508 non-null  str
 6   crt_97[H]                   14508 non-null  str
 7   crt_218[I]                  14508 non-null  str
 8   crt_220[A]                  14508 non-null  str
 9   crt_271[Q]                  14508 non-null  str
 10  crt_326[N]                  14508 non-null  str
 11  crt_333[T]                  14508 non-null  str
 12  crt_353[G]                  14508 non-null  str
 13  crt_356[I]                  14508 non-null  str
 14  crt_371[R]                  14508 non-null  str
 15  dhfr_16[N]                  14508 non-null  str
 16  dhfr_51[N]                  14508 non-null  str
 17  dhfr_59[C]                  14508 non-null  str
 18  dhfr_108[S]                 14508 non-null  str
 19  dhfr_164[I]                 14508 non-null  str
 20  dhfr_306[S]                 14508 non-null  str
 21  dhps_436[S]                 14508 non-null  str
 22  dhps_437[G]                 14508 non-null  str
 23  dhps_540[K]                 14508 non-null  str
 24  dhps_581[A]                 14508 non-null  str
 25  dhps_613[A]                 14508 non-null  str
 26  exo_415[E]                  14508 non-null  str
 27  mdr1_86[N]                  14508 non-null  str
 28  mdr1_184[Y]                 14508 non-null  str
 29  mdr1_1034[S]                14508 non-null  str
 30  mdr1_1042[N]                14508 non-null  str
 31  mdr1_1226[F]                14508 non-null  str
 32  mdr1_1246[D]                14508 non-null  str
 33  arps10_127-128[VD]          14508 non-null  str
 34  fd_193[D]                   14508 non-null  str
 35  mdr2_484[T]                 14508 non-null  str
 36  kelch13_349-726_ns_changes  14508 non-null  str
 37  mdr1_dup_call               14508 non-null  str
 38  pm2_dup_call                14508 non-null  str
 39  ARTresistant                14508 non-null  str
 40  CQresistant                 14508 non-null  str
 41  MQresistant                 14508 non-null  str
 42  PPQresistant                14508 non-null  str
 43  PYRresistant                14508 non-null  str
 44  SDXresistant                14508 non-null  str
dtypes: str(45)
memory usage: 5.1 MB

# Handling data type

In [39]:
genotype.value_counts()

crt_72[C]  crt_74[M]  crt_75[N]  crt_76[K]  crt_72-76[CVMNK]  crt_93[T]  crt_97[H]  crt_218[I]  crt_220[A]  crt_271[Q]  crt_326[N]  crt_333[T]  crt_353[G]  crt_356[I]  crt_371[R]  dhfr_16[N]  dhfr_51[N]  dhfr_59[C]  dhfr_108[S]  dhfr_164[I]  dhfr_306[S]  dhps_436[S]  dhps_437[G]  dhps_540[K]  dhps_581[A]  dhps_613[A]  exo_415[E]  mdr1_86[N]  mdr1_184[Y]  mdr1_1034[S]  mdr1_1042[N]  mdr1_1226[F]  mdr1_1246[D]  arps10_127-128[VD]  fd_193[D]  mdr2_484[T]  kelch13_349-726_ns_changes  mdr1_dup_call  pm2_dup_call  ARTresistant  CQresistant   MQresistant   PPQresistant  PYRresistant  SDXresistant
Sensitive  Sensitive  Sensitive  Sensitive  Sensitive         Sensitive  Sensitive  Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Resistant   Resistant   Resistant   Resistant    Sensitive    Sensitive    Sensitive    Resistant    Resistant    Sensitive    Sensitive    Sensitive   Sensitive   Sensitive    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Missing                     Sensitive      Sensitive     sensitive     sensitive     sensitive     sensitive     resistant     resistant       731
                                                                                                                                                                                                                                                                                                                                                        Resistant    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Missing                     Sensitive      Sensitive     sensitive     sensitive     sensitive     sensitive     resistant     resistant       377
                                                                                                                                                                                                                                                                                         Sensitive    Sensitive    Sensitive    Sensitive   Sensitive   Sensitive    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Missing                     Sensitive      Sensitive     sensitive     sensitive     sensitive     sensitive     resistant     resistant       283
                                                                                                                                                                                                                                                                                                                                                        Resistant    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Missing                     Sensitive      Sensitive     sensitive     sensitive     sensitive     sensitive     resistant     resistant       271
                                                                                                                                                                                                                                                                                         Resistant    Sensitive    Sensitive    Sensitive   Sensitive   Sensitive    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Missing                     Sensitive      Sensitive     sensitive     sensitive     undetermined  undetermined  resistant     resistant       247
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ...
                                 Resistant  Sensitive         Sensitive  Sensitive  Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Resistant   Resistant   Resistant   Resistant    Sensitive    Sensitive    Sensitive    Resistant    Sensitive    Resistant    Resistant    Sensitive   Sensitive   Resistant    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Missing                     Sensitive      Sensitive     sensitive     undetermined  undetermined  undetermined  resistant     resistant         1
                                 Sensitive  Sensitive         Sensitive  Sensitive  Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Resistant   Resistant   Resistant   Resistant    Sensitive    Sensitive    Sensitive    Resistant    Sensitive    Resistant    Resistant    Sensitive   Sensitive   Resistant    Sensitive     Sensitive     Resistant     Sensitive     Sensitive           Sensitive  Sensitive    Rare                        Sensitive      Undetermined  undetermined  sensitive     undetermined  undetermined  resistant     resistant         1
                                 Resistant  Sensitive         Sensitive  Sensitive  Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Resistant   Resistant   Resistant   Resistant    Sensitive    Sensitive    Sensitive    Resistant    Sensitive    Sensitive    Sensitive    Sensitive   Sensitive   Sensitive    Sensitive     Sensitive     Sensitive     Sensitive     Sensitive           Sensitive  Sensitive    Rare                        Undetermined   Sensitive     undetermined  undetermined  undetermined  undetermined  resistant     resistant         1
                                 Sensitive  Sensitive         Sensitive  Sensitive  Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Sensitive   Resistant   Resistant   Resistant   Resistant    Sensitive    Sensitive    Resistant    Resistant    Sensitive    Sensitive    Sensitive    Sensitive   Sensitive   Resistant    Sensitive     Sensitive     Sensitive     Resistant     Sensitive           Sensitive  Sensitive    Rare                        Undetermined   Undetermined  undetermined  sensitive     undetermined  undetermined  resistant     undetermined      1
           Resistant  Resistant  Resistant  Resistant         Sensitive  Sensitive  Sensitive   Resistant   Resistant   Resistant   Resistant   Sensitive   Resistant   Resistant   Resistant   Resistant   Resistant   Resistant    Sensitive    Sensitive    Sensitive    Resistant    Sensitive    Sensitive    Sensitive    Sensitive   Sensitive   Resistant    Resistant     Resistant     Resistant     Resistant     Sensitive           Sensitive  Resistant    Rare                        Undetermined   Undetermined  undetermined  resistant     undetermined  undetermined  resistant     resistant         1
Name: count, Length: 3893, dtype: int64

In [40]:
genotype[['pm2_dup_call','mdr1_dup_call']].value_counts()

pm2_dup_call  mdr1_dup_call
Sensitive     Sensitive        10458
Undetermined  Undetermined      2036
              Sensitive         1233
Sensitive     Undetermined       781
Name: count, dtype: int64

In [51]:
# changing numerical columns to int

### Handling/ encoding columns

In [44]:
genotype.columns

Index(['crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]', 'crt_72-76[CVMNK]',
       'crt_93[T]', 'crt_97[H]', 'crt_218[I]', 'crt_220[A]', 'crt_271[Q]',
       'crt_326[N]', 'crt_333[T]', 'crt_353[G]', 'crt_356[I]', 'crt_371[R]',
       'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]', 'dhfr_108[S]', 'dhfr_164[I]',
       'dhfr_306[S]', 'dhps_436[S]', 'dhps_437[G]', 'dhps_540[K]',
       'dhps_581[A]', 'dhps_613[A]', 'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]',
       'mdr1_1034[S]', 'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]',
       'arps10_127-128[VD]', 'fd_193[D]', 'mdr2_484[T]',
       'kelch13_349-726_ns_changes', 'mdr1_dup_call', 'pm2_dup_call',
       'ARTresistant', 'CQresistant', 'MQresistant', 'PPQresistant',
       'PYRresistant', 'SDXresistant'],
      dtype='str')

In [49]:
print(len(col_unique))

45

In [46]:
col_unique = {}
for col in genotype.columns:
    unique = genotype[col].unique()
    col_unique[col] = unique

In [50]:
for col, values in col_unique.items():
    print(f"\n{col}")
    print(values)

crt_72[C]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_74[M]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_75[N]
<StringArray>
['Sensitive', 'Resistant', 'Rare']
Length: 3, dtype: str

crt_76[K]
<StringArray>
['Resistant', 'Sensitive']
Length: 2, dtype: str

crt_72-76[CVMNK]
<StringArray>
['Sensitive', 'Resistant', 'Rare']
Length: 3, dtype: str

crt_93[T]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_97[H]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_218[I]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_220[A]
<StringArray>
['Sensitive', 'Resistant', 'Rare']
Length: 3, dtype: str

crt_271[Q]
<StringArray>
['Resistant', 'Sensitive']
Length: 2, dtype: str

crt_326[N]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_333[T]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_353[G]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_356[I]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

crt_371[R]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

dhfr_16[N]
<StringArray>
['Resistant']
Length: 1, dtype: str

dhfr_51[N]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

dhfr_59[C]
<StringArray>
['Sensitive', 'Resistant', 'Rare']
Length: 3, dtype: str

dhfr_108[S]
<StringArray>
['Resistant', 'Sensitive']
Length: 2, dtype: str

dhfr_164[I]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

dhfr_306[S]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

dhps_436[S]
<StringArray>
['Sensitive', 'Resistant', 'Rare']
Length: 3, dtype: str

dhps_437[G]
<StringArray>
['Resistant']
Length: 1, dtype: str

dhps_540[K]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

dhps_581[A]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

dhps_613[A]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

exo_415[E]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr1_86[N]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr1_184[Y]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr1_1034[S]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr1_1042[N]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr1_1226[F]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr1_1246[D]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

arps10_127-128[VD]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

fd_193[D]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

mdr2_484[T]
<StringArray>
['Sensitive', 'Resistant']
Length: 2, dtype: str

kelch13_349-726_ns_changes
<StringArray>
['Missing', 'Rare']
Length: 2, dtype: str

mdr1_dup_call
<StringArray>
['Sensitive', 'Undetermined']
Length: 2, dtype: str

pm2_dup_call
<StringArray>
['Sensitive', 'Undetermined']
Length: 2, dtype: str

ARTresistant
<StringArray>
['sensitive', 'undetermined']
Length: 2, dtype: str

CQresistant
<StringArray>
['undetermined', 'resistant', 'sensitive']
Length: 3, dtype: str

MQresistant
<StringArray>
['sensitive', 'undetermined']
Length: 2, dtype: str

PPQresistant
<StringArray>
['sensitive', 'undetermined']
Length: 2, dtype: str

PYRresistant
<StringArray>
['undetermined', 'resistant', 'sensitive']
Length: 3, dtype: str

SDXresistant
<StringArray>
['undetermined', 'sensitive', 'resistant']
Length: 3, dtype: str

In [ ]:
def encoding(value,column):
  # ---------- Special: kelch13 ----------
if column == "kelch13_349-726_ns_changes":

    # Missing or unresolved
    if value == 'rare':
        value == int(0)
    elif value == 'sensitive':
        value == int(1)
    else

def encoding(value):