In [3]:
import pandas as pd

In [4]:
# Import the metadata asa csv using pandas

import pandas as pd

metadata = pd.read_csv("../data/raw/Pf8-samples.csv")

In [5]:
metadata.head()
# This codes displays the first few (6) lines of the data

,sample_id,year,qc_pass,study_id,region,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,FP0008-C,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,FP0009-C,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,FP0010-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,FP0011-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,FP0012-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [6]:
metadata.shape

(32995, 15)

In [7]:
metadata.columns
metadata.columns.tolist()

['sample_id',
 'year',
 'qc_pass',
 'study_id',
 'region',
 'country',
 'country_id',
 'site',
 'site_id',
 'ARTresistant',
 'CQresistant',
 'MQresistant',
 'PPQresistant',
 'PYRresistant',
 'SDXresistant']

In [8]:
# looking for missing values
metadata.isnull().sum()

sample_id           0
year                0
qc_pass             0
study_id            0
region          32995
country             0
country_id          0
site                0
site_id             0
ARTresistant     8586
CQresistant      8586
MQresistant      8586
PPQresistant     8586
PYRresistant     8586
SDXresistant     8586
dtype: int64

In [9]:
# Available contries
metadata["country"].value_counts()

country
Ghana                               6653
Vietnam                             2700
Mali                                2428
Cambodia                            2282
Kenya                               2142
Gambia                              1998
Laos                                1994
Bangladesh                          1658
Democratic Republic of the Congo    1549
Mozambique                          1348
Nigeria                             1303
Myanmar                             1268
Thailand                            1157
Tanzania                            1144
Malawi                               681
Sudan                                356
Benin                                334
India                                318
Cameroon                             294
Papua New Guinea                     251
Guinea                               199
Colombia                             167
Senegal                              155
Indonesia                            133
Peru                                 106
Mauritania                           104
Côte d'Ivoire                         71
Gabon                                 59
Burkina Faso                          58
Ethiopia                              35
Madagascar                            25
Uganda                                15
Honduras                               8
Venezuela                              2
Name: count, dtype: int64

In [10]:
# Represented years
metadata["year"].value_counts().sort_index()

year
1966       7
1967       7
1968      17
1969      14
1970      15
1971       1
1984     189
1990      18
1991       7
1993       5
1994      53
1995      57
1996      66
1997      66
1998      65
1999      14
2000      87
2001      77
2002     139
2003     181
2004     171
2005     185
2006      80
2007     342
2008     637
2009     356
2010     744
2011    1506
2012    1292
2013    2008
2014    2575
2015    2812
2016    4000
2017    4343
2018    5707
2019    2419
2020    1705
2021      88
2022     940
Name: count, dtype: int64

In [11]:
# Filter by quality control
metadata = metadata[metadata["qc_pass"] == True]
# Reoves all the columns that failed the quality control

In [12]:
print(metadata)
#To confirm if the failed quality contrls have been removed

       sample_id  year  qc_pass  study_id  region     country country_id  \
0       FP0008-C  2014     True      1147     NaN  Mauritania         MR
1       FP0009-C  2014     True      1147     NaN  Mauritania         MR
2      FP0010-CW  2014     True      1147     NaN  Mauritania         MR
3      FP0011-CW  2014     True      1147     NaN  Mauritania         MR
4      FP0012-CW  2014     True      1147     NaN  Mauritania         MR
...          ...   ...      ...       ...     ...         ...        ...
32814   SPT92049  2019     True      1306     NaN     Nigeria         NG
32818   SPT92054  2019     True      1306     NaN     Nigeria         NG
32821   SPT92057  2019     True      1306     NaN     Nigeria         NG
32993   SPT94772  2017     True      1268     NaN      Gambia         GM
32994   SPT94773  2017     True      1268     NaN      Gambia         GM

                 site         site_id  ARTresistant   CQresistant  \
0      Hodh el Gharbi  Hodh el Gharbi     sensitive  undetermined
1      Hodh el Gharbi  Hodh el Gharbi     sensitive     resistant
2      Hodh el Gharbi  Hodh el Gharbi     sensitive  undetermined
3      Hodh el Gharbi  Hodh el Gharbi     sensitive  undetermined
4      Hodh el Gharbi  Hodh el Gharbi     sensitive     resistant
...               ...             ...           ...           ...
32814             Oyo             Oyo  undetermined     sensitive
32818             Oyo             Oyo     sensitive     sensitive
32821             Oyo             Oyo  undetermined     sensitive
32993         Western         Western  undetermined     resistant
32994         Western         Western     sensitive     resistant

        MQresistant  PPQresistant  PYRresistant  SDXresistant
0         sensitive     sensitive  undetermined  undetermined
1         sensitive     sensitive     resistant     sensitive
2      undetermined  undetermined     resistant     resistant
3      undetermined  undetermined     resistant  undetermined
4      undetermined  undetermined     resistant     sensitive
...             ...           ...           ...           ...
32814  undetermined  undetermined     resistant  undetermined
32818  undetermined  undetermined     resistant     resistant
32821  undetermined  undetermined     resistant     resistant
32993  undetermined  undetermined     resistant     resistant
32994     sensitive     sensitive     resistant     resistant

[24409 rows x 15 columns]

In [13]:
# Filter by country/Region
# First select or the interested countries ie East and West African countries
# Grouped he ountriess as East and West Afrian contries
east_africa = [
    "Kenya",
    "Tanzania",
    "Uganda",
    "Rwanda",
    "Burundi",
    "Ethiopia",
    "South Sudan",
    "Mozambique"
]

west_africa = [
    "Ghana",
    "Nigeria",
    "Mali",
    "Burkina Faso",
    "Senegal",
    "Guinea",
    "Sierra Leone",
    "Liberia",
    "Benin",
    "Togo",
    "Niger",
    "Côte d'Ivoire",
    "The Gambia",
    "Cameroon"   # Include only if your project considers it part of the West/Central comparison
]

In [14]:
# list all east African countries 
east_africa = [
    "Kenya",
    "Uganda",
    "Tanzania",
    "Rwanda",
    "Burundi",
    "Ethiopia",
    "South Sudan",
    "Sudan",
    "Somalia",
    "Eritrea",
    "Djibouti"
]

East_Africa_metadata = metadata[metadata["country"].isin(east_africa)]

In [15]:
# All the east Afrian countries in out metadata
East_Africa_metadata["country"].value_counts()

country
Kenya       1934
Tanzania    1025
Sudan        115
Ethiopia      22
Uganda        10
Name: count, dtype: int64

In [16]:
#list of all thee west african countries
west_africa = [
    "Ghana",
    "Nigeria",
    "Mali",
    "Burkina Faso",
    "Senegal",
    "Guinea",
    "Sierra Leone",
    "Liberia",
    "Benin",
    "Togo",
    "Niger",
    "Côte d'Ivoire",
    "The Gambia",
    "Cameroon"   # Include only if your project considers it part of the West/Central comparison
]

west_Africa_metadata = metadata[metadata["country"].isin(west_africa)]

West_Africa_metadata = metadata[metadata["country"].isin(west_africa)]

In [17]:
# List of west african countries in out metadata
west_Africa_metadata["country"].value_counts()

country
Ghana            4905
Mali             1253
Nigeria           400
Cameroon          261
Senegal           151
Guinea            149
Benin             145
Côte d'Ivoire      71
Burkina Faso       56
Name: count, dtype: int64

In [18]:
# Grouping all the east African countries with their amount of data in each year
east_country_year = pd.crosstab(
    East_Africa_metadata["country"],
    East_Africa_metadata["year"]
)

# Sort years
east_country_year = east_country_year.reindex(
    sorted(east_country_year.columns), axis=1
)

east_country_year

year,1994,1995,1996,1997,1998,1999,2000,2003,2004,2005,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
country,,,,,,,,,,,,,,,,,,,,,
Ethiopia,0,0,0,0,0,0,0,0,0,0,...,0,0,12,0,10,0,0,0,0,0
Kenya,53,57,65,61,64,12,18,56,65,59,...,72,84,82,123,43,49,51,261,244,44
Sudan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,18,19,78,0,0,0
Tanzania,0,0,0,0,0,0,0,0,0,0,...,0,0,269,273,0,4,0,0,432,0
Uganda,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
# making the data available as csv
east_country_year.to_csv("east-country_year.csv",index= True)

In [20]:
# Grouping all the west African countries with their amount of data in each year

west_country_year = pd.crosstab(
    West_Africa_metadata["country"],
    West_Africa_metadata["year"]
)

west_country_year = west_country_year.reindex(
    sorted(west_country_year.columns), axis=1
)

west_country_year

year,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
country,,,,,,,,,,,,,,,
Benin,0,0,0,0,0,0,0,36,0,109,0,0,0,0,0
Burkina Faso,0,56,0,0,0,0,0,0,0,0,0,0,0,0,0
Cameroon,0,0,0,0,0,0,231,0,0,9,21,0,0,0,0
Côte d'Ivoire,0,0,0,0,0,0,53,18,0,0,0,0,0,0,0
Ghana,0,0,120,168,102,87,247,480,372,307,698,1864,219,226,15
Guinea,0,0,0,0,149,0,0,0,0,0,0,0,0,0,0
Mali,85,0,0,0,0,3,329,134,166,392,42,14,44,44,0
Nigeria,0,10,0,0,1,4,0,24,0,0,99,22,29,211,0
Senegal,0,0,0,0,0,0,64,27,60,0,0,0,0,0,0

In [21]:
# making the data available as csv
west_country_year.to_csv("west-country_year.csv",index= True)

In [22]:
# merging east and west Africa that is qrouped yearly
east_year = East_Africa_metadata["year"].value_counts().sort_index()
west_year = West_Africa_metadata["year"].value_counts().sort_index()

regional_year = pd.DataFrame(
    [east_year, west_year],
    index=["East Africa", "West Africa"]
).fillna(0).astype(int)

regional_year

year,1994,1995,1996,1997,1998,1999,2000,2003,2004,2005,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
East Africa,53,57,65,61,64,12,18,56,65,59,...,84,363,396,71,72,129,261,676,44,0
West Africa,0,0,0,0,0,0,0,0,0,0,...,94,924,719,598,817,860,1900,292,481,15

In [23]:
# making the data available as csv
regional_year.to_csv("regional_year.csv",index= True)

In [24]:
# Filter the years from 2019 to 2019
East_Africa_2010_2019 = East_Africa_metadata[
    East_Africa_metadata["year"].between(2010, 2019)
]
West_Africa_2010_2019 = West_Africa_metadata[
    West_Africa_metadata["year"].between(2010, 2019)
]

In [25]:
# Check that every year has at least 71 samples
print(East_Africa_2010_2019["year"].value_counts().sort_index())

print(West_Africa_2010_2019["year"].value_counts().sort_index())

year
2010    147
2011     72
2012     84
2013    363
2014    396
2015     71
2016     72
2017    129
2018    261
2019    676
Name: count, dtype: int64
year
2010     168
2011     252
2012      94
2013     924
2014     719
2015     598
2016     817
2017     860
2018    1900
2019     292
Name: count, dtype: int64

In [26]:
# Randomly select 71 samples from each year in East Africa
East_Africa_71 = (
    East_Africa_2010_2019
    .groupby("year", group_keys=False)
    .sample(n=71, random_state=42)
)

In [27]:
# # Randomly select 71 samples from each year in west Africa

West_Africa_71 = (
    West_Africa_2010_2019
    .groupby("year", group_keys=False)
    .sample(n=71, random_state=42)
)

In [28]:
# Verify
East_Africa_71["year"].value_counts().sort_index()

year
2010    71
2011    71
2012    71
2013    71
2014    71
2015    71
2016    71
2017    71
2018    71
2019    71
Name: count, dtype: int64

In [29]:
# verify
West_Africa_71["year"].value_counts().sort_index()

year
2010    71
2011    71
2012    71
2013    71
2014    71
2015    71
2016    71
2017    71
2018    71
2019    71
Name: count, dtype: int64

In [30]:
# East Africa: Total samples per country (across all years)
East_Africa_71["country"].value_counts().sort_index()

country
Ethiopia     12
Kenya       427
Sudan        83
Tanzania    184
Uganda        4
Name: count, dtype: int64

In [31]:
# West Africa: Total samples per country (across all years)
West_Africa_71["country"].value_counts().sort_index()

country
Benin              8
Cameroon          27
Côte d'Ivoire      5
Ghana            479
Guinea            48
Mali             106
Nigeria           20
Senegal           17
Name: count, dtype: int64

In [36]:
West_Africa_71.head()

,sample_id,year,qc_pass,study_id,region,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
2550,PF0342-C,2010,True,1017,NaN,Ghana,GH,Upper East,Upper East,sensitive,sensitive,sensitive,sensitive,resistant,resistant
2435,PF0192-C,2010,True,1017,NaN,Ghana,GH,Upper East,Upper East,sensitive,sensitive,sensitive,sensitive,resistant,undetermined
2529,PF0314-C,2010,True,1017,NaN,Ghana,GH,Upper East,Upper East,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
2434,PF0191-C,2010,True,1017,NaN,Ghana,GH,Upper East,Upper East,sensitive,sensitive,sensitive,sensitive,undetermined,resistant
2562,PF0355-C,2010,True,1017,NaN,Ghana,GH,Upper East,Upper East,sensitive,sensitive,sensitive,sensitive,resistant,resistant

In [32]:
# To see how many samples came from each country in each year
east_country_year = pd.crosstab(
    East_Africa_71["country"],
    East_Africa_71["year"]
)

east_country_year

year      2010  2011  2012  2013  2014  2015  2016  2017  2018  2019
country
Ethiopia     0     0     0     2     0    10     0     0     0     0
Kenya       40    71    71    20    16    43    48    25    71    22
Sudan        0     0     0     0     0    18    19    46     0     0
Tanzania    27     0     0    49    55     0     4     0     0    49
Uganda       4     0     0     0     0     0     0     0     0     0

In [33]:
# To see how many samples came from each country in each year
west_country_year = pd.crosstab(
    West_Africa_71["country"],
    West_Africa_71["year"]
)

west_country_year

year           2010  2011  2012  2013  2014  2015  2016  2017  2018  2019
country
Benin             0     0     0     0     1     0     7     0     0     0
Cameroon          0     0     0    23     0     0     2     2     0     0
Côte d'Ivoire     0     0     0     2     3     0     0     0     0     0
Ghana            71    23    64    17    45    44    30    62    69    54
Guinea            0    48     0     0     0     0     0     0     0     0
Mali              0     0     3    25    14    19    32     3     0    10
Nigeria           0     0     4     0     3     0     0     4     2     7
Senegal           0     0     0     4     5     8     0     0     0     0

In [37]:
West_Africa_71.to_csv("../processed/west-country_year2010-2019.csv",index= True)

In [38]:
East_Africa_71.to_csv("../processed/east-country_year2010-2019.csv",index= True)