In [ ]:
import numpy as np
import pandas as pd
import re

In [ ]:
#import genotype data
genotype = pd.read_csv(
    "../data/raw/Pf8_drug_resistance_marker_genotypes.tsv",
    sep="\t"
)

In [ ]:
# viewing data
genotype

,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],...,mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],kelch13_349-726_ns_changes,mdr1_dup_call,pm2_dup_call
0,FP0008-C,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
1,FP0009-C,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,Y,VD,D,T,NaN,0,0
2,FP0010-CW,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
3,FP0011-CW,C,"I,M","E,N","T,K","CVIET,CVMNK",T,H,I,"S,A",...,S,N,F,D,VD,D,T,NaN,0,0
4,FP0012-CW,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,D,VD,D,T,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24404,SPT92049,C,M,N,K,CVMNK,T,H,I,A,...,S,N,F,-,VD,D,T,-,-1,-1
24405,SPT92054,C,M,N,K,CVMNK,T,H,I,A,...,S,N,F,D,VD,D,T,NaN,0,-1
24406,SPT92057,C,M,N,K,CVMNK,T,H,I,A,...,S,N,F,D,VD,D,T,-,-1,-1
24407,SPT94772,C,I,E,T,CVIET,T,H,I,S,...,-,-,-,-,VD,D,-,-,-1,-1
24408,SPT94773,C,I,E,T,CVIET,T,H,I,S,...,S,N,F,D,VD,D,T,NaN,0,0

### Data exploration

In [ ]:
print(genotype["crt_76[K]"].value_counts(dropna=False))

crt_76[K]
T       12432
K       10768
T,K       607
K,T       550
-          48
T,Q         3
T,Q*        1
Name: count, dtype: int64

In [ ]:
# viewing all column count data
genotype_dic = {}
for col in genotype.columns:
    value_count = genotype[col].value_counts(dropna = False)
    genotype_dic[col] = value_count

In [ ]:
print(genotype_dic)

{'Sample': Sample
FP0008-C     1
FP0009-C     1
FP0010-CW    1
FP0011-CW    1
FP0012-CW    1
            ..
SPT92049     1
SPT92054     1
SPT92057     1
SPT94772     1
SPT94773     1
Name: count, Length: 24409, dtype: int64, 'crt_72[C]': crt_72[C]
C      23955
S        402
-         34
S,C        6
C,S        5
C,Y        5
Y          2
Name: count, dtype: int64, 'crt_74[M]': crt_74[M]
I      11883
M      11318
I,M      612
M,I      544
-         52
Name: count, dtype: int64, 'crt_75[N]': crt_75[N]
N       11205
E       11017
D         839
E,N       594
N,E       525
E,D        71
D,E        62
-          52
N,D        19
D,N         9
E,K         7
N,E*        3
E,N*        3
K           2
K,E         1
Name: count, dtype: int64, 'crt_76[K]': crt_76[K]
T       12432
K       10768
T,K       607
K,T       550
-          48
T,Q         3
T,Q*        1
Name: count, dtype: int64, 'crt_72-76[CVMNK]': crt_72-76[CVMNK]
CVIET           10898
CVMNK           10749
CVIDT             839
CVIET,CVMNK       585
CVMNK,CVIET       518
SVMNT             402
CVMET             105
CVIET,CVIDT        69
-                  64
CVIDT,CVIET        62
CVMNT              34
CVMNK,CVIDT        18
CVIDT,CVMNK         9
CVIET,CVMNK*        7
CVMNK,CVIET*        5
SVMNT,CVMNK*        4
CVMNK,SVMNT*        4
CVIET,YVIET         3
CVIET,CVMNT         3
CVIET,CVIKT         2
YVIET               2
CVMNT,CVMET         2
CVMET,CVMNT         2
CVIET,CVIEK         2
CVIET,CVMKQ         2
CVMNK,CIMNK         2
CVIET,CVMKT         1
CVIET,CVMEK         1
CVIET,SVMNT*        1
CIIET,CVIET         1
CVIET,CVINK         1
CVIET,CVMDT         1
SVMNT,CVMET*        1
CVIET,CVIDK         1
CVIET,CIIET         1
CVMNK,CVIDT*        1
CVIET,CVMKQ*        1
CVIET,CVMKK         1
SVMNT,CVMNT         1
CVMKQ,CVIET         1
CVMNK,YVMNK         1
CVMNK,CIINK         1
CVMNK,YIMNK         1
Name: count, dtype: int64, 'crt_93[T]': crt_93[T]
T      23301
S        944
S,T       77
T,S       54
-         28
I          2
S,L        1
T,I        1
T,T        1
Name: count, dtype: int64, 'crt_97[H]': crt_97[H]
H      23955
Y        198
Q        108
L         60
-         31
H,Y       25
Y,H       11
H,L        6
L,H        5
H,Q        3
Q,H        3
H,H        3
Y,Y        1
Name: count, dtype: int64, 'crt_218[I]': crt_218[I]
I      23087
-        707
F        552
I,F       39
F,I       24
Name: count, dtype: int64, 'crt_220[A]': crt_220[A]
S      11676
A      10609
-       1108
A,S      574
S,A      430
A,A        9
S,S        1
A,T        1
S,F        1
Name: count, dtype: int64, 'crt_271[Q]': crt_271[Q]
E      11902
Q      11286
Q,E      535
E,Q      491
-        189
Q,Q        3
E,         2
Q,         1
Name: count, dtype: int64, 'crt_326[N]': crt_326[N]
N      17557
S       5773
D        423
-        372
N,S      142
S,N      131
D,N        8
N,D        3
Name: count, dtype: int64, 'crt_333[T]': crt_333[T]
T       22953
S         846
A         293
-         165
S,T        71
T,S        69
A,T         6
T,T         1
T,A         1
T,G*        1
S,A         1
S,A*        1
T,N         1
Name: count, dtype: int64, 'crt_353[G]': crt_353[G]
G      24278
V         87
-         29
G,V        9
V,G        4
G,D        1
G,G        1
Name: count, dtype: int64, 'crt_356[I]': crt_356[I]
I      14846
T       8286
L        435
I,T      368
T,I      364
-         98
L,I        6
I,L        6
Name: count, dtype: int64, 'crt_371[R]': crt_371[R]
R      11954
I      11047
R,I      661
I,R      584
-         87
T         72
T,R        3
I,T        1
Name: count, dtype: int64, 'dhfr_16[N]': dhfr_16[N]
A      24304
-        104
A,S        1
Name: count, dtype: int64, 'dhfr_51[N]': dhfr_51[N]
I      18360
N       4029
I,N      977
N,I      746
-        297
Name: count, dtype: int64, 'dhfr_59[C]': dhfr_59[C]
R      20722
C       2034
R,C      828
C,R      498
-        323
Y,R        2
R,Y        1
Y,C        1
Name: count, dtype: int64, 'dhfr_108[S]': dhfr_108[S]
N      21964
S       1215
N,S      471
-        414
S,N      344
N,T        1
Name: count, dtype: int64, 'dhfr_164[I]': dhfr_164[I]
I      19106
L       4690
-        269
I,L      175
L,I      167
M          1
M,I        1
Name: count, dtype: int64, 'dhfr_306[S]': dhfr_306[S]
S      23882
-        261
F        231
S,F       18
F,S       17
Name: count, dtype: int64, 'dhps_436[S]': dhps_436[S]
S       16149
A        5564
A,S      1122
S,A       890
-         332
F          93
H          27
F,A        27
C          25
A,F        23
Y          20
S,F        20
A,Y        16
S,H        14
Y,A        14
S,C        12
F,S        12
H,S        11
Y,S         8
C,S         4
S,Y         4
C,A         3
A,F*        3
F,A*        2
S,H*        1
H,F         1
S,L         1
Y,F         1
Y,A*        1
S,S         1
S,D*        1
A,A         1
A,V         1
H,A*        1
S,V         1
S,G*        1
A,H*        1
F,C         1
Name: count, dtype: int64, 'dhps_437[G]': dhps_437[G]
G      19270
A       3601
G,A      686
A,G      582
-        270
Name: count, dtype: int64, 'dhps_540[K]': dhps_540[K]
K       12848
E        7536
N        2747
E,K       395
-         363
K,E       327
N,E        66
E,N        57
N,K        33
K,N        13
Y           9
E,N*        5
N,E*        3
K,Y         2
Y,K         2
K,K         2
K,D*        1
Name: count, dtype: int64, 'dhps_581[A]': dhps_581[A]
A      18694
G       4798
-        365
G,A      281
A,G      266
G,G        4
A,A        1
Name: count, dtype: int64, 'dhps_613[A]': dhps_613[A]
A      22744
S        665
A,S      365
-        305
S,A      252
T         54
T,A       13
A,T       10
A,V        1
Name: count, dtype: int64, 'exo_415[E]': exo_415[E]
E      21720
G       2535
G,E       64
E,G       56
-         33
E,V        1
Name: count, dtype: int64, 'mdr1_86[N]': mdr1_86[N]
N      21140
Y       1895
N,Y      598
Y,N      438
-        334
N,F        2
N,I        1
N,G        1
Name: count, dtype: int64, 'mdr1_184[Y]': mdr1_184[Y]
Y      10527
F      10268
F,Y     1567
Y,F     1295
-        752
Name: count, dtype: int64, 'mdr1_1034[S]': mdr1_1034[S]
S      23122
-       1221
C         51
I         10
I,S        2
S,C        1
C,S        1
S,S        1
Name: count, dtype: int64, 'mdr1_1042[N]': mdr1_1042[N]
N      22940
-       1077
D        381
D,N        6
N,D        5
Name: count, dtype: int64, 'mdr1_1226[F]': mdr1_1226[F]
F      22624
Y        873
-        745
F,Y       88
Y,F       75
F,F        4
Name: count, dtype: int64, 'mdr1_1246[D]': mdr1_1246[D]
D      22711
-        775
Y        589
D,Y      194
Y,D      140
Name: count, dtype: int64, 'arps10_127-128[VD]': arps10_127-128[VD]
VD        19163
MH         4641
VY          221
-            97
VH           93
MH,VD        86
VD,MH        61
MH,VY*       10
VD,VY         6
VY,VD         6
VY,MH*        5
MH,VH         4
VH,VD         3
VH,MH         3
VH,VY         3
VD,VH         3
VD,VD         2
VY,VH         1
VN,VD         1
Name: count, dtype: int64, 'fd_193[D]': fd_193[D]
D      18936
Y       5238
D,Y       90
-         68
Y,D       68
D,N        3
Y,         2
N          2
N,D        1
D,D        1
Name: count, dtype: int64, 'mdr2_484[T]': mdr2_484[T]
T      18642
I       5245
I,T      179
-        179
T,I      164
Name: count, dtype: int64, 'kelch13_349-726_ns_changes': kelch13_349-726_ns_changes
NaN      17077
C580Y     3016
-         2845
R539T      132
P441L      122
         ...
d641n        1
S364Y        1
s477y        1
T350S        1
c469y        1
Name: count, Length: 266, dtype: int64, 'mdr1_dup_call': mdr1_dup_call
 0    19512
-1     4195
 1      702
Name: count, dtype: int64, 'pm2_dup_call': pm2_dup_call
 0    17610
-1     4719
 1     2080
Name: count, dtype: int64}

In [ ]:
genotype.columns

Index(['Sample', 'crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]',
       'crt_72-76[CVMNK]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]',
       'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]',
       'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]',
       'dhfr_108[S]', 'dhfr_164[I]', 'dhfr_306[S]', 'dhps_436[S]',
       'dhps_437[G]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]',
       'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]',
       'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]',
       'fd_193[D]', 'mdr2_484[T]', 'kelch13_349-726_ns_changes',
       'mdr1_dup_call', 'pm2_dup_call'],
      dtype='str')

In [ ]:
# handling kelchi data
genotype['kelch13_349-726_ns_changes'].unique()

<StringArray>
[    nan,     '-', 'a676s', 'p441s', 'E612D', 'A676S', 'S522C', 'a578s',
 's522i', 'e509d',
 ...
 'v566i', 'p527s', 'a427v', 'v566l', 'd641n', 'S364Y', 'V487E', 's477y',
 'T350S', 'c469y']
Length: 266, dtype: str

## Classifying known biomarkers

In [ ]:
genotype.columns

Index(['Sample', 'crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]',
       'crt_72-76[CVMNK]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]',
       'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]',
       'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]',
       'dhfr_108[S]', 'dhfr_164[I]', 'dhfr_306[S]', 'dhps_436[S]',
       'dhps_437[G]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]',
       'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]',
       'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]',
       'fd_193[D]', 'mdr2_484[T]', 'kelch13_349-726_ns_changes',
       'mdr1_dup_call', 'pm2_dup_call'],
      dtype='str')

In [ ]:
# creating a dataframe for known resistance biomakers
encoded = pd.DataFrame()

encoded["Sample"] = genotype["Sample"]

In [ ]:
# markers associated with drug resistance

associated_marker = {

    "dhfr_51[N]": {
        "gene": "dhfr",
        "wildtype": "N",
        "resistant": {"I"}
    },

    "dhfr_59[C]": {
        "gene": "dhfr",
        "wildtype": "C",
        "resistant": {"R"}
    },

    "dhfr_164[I]": {
        "gene": "dhfr",
        "wildtype": "I",
        "resistant": {"L"}
    },


    "dhps_540[K]": {
        "gene": "dhps",
        "wildtype": "K",
        "resistant": {"E"}
    },

    "dhps_581[A]": {
        "gene": "dhps",
        "wildtype": "A",
        "resistant": {"G"}
    },

    "dhps_613[A]": {
        "gene": "dhps",
        "wildtype": "A",
        "resistant": {"S", "T"}
    }
}

In [ ]:
marker_info = {
    "crt_76[K]": {
        "wildtype": "K",
        "resistant": {"T"}
    },

    "dhfr_108[S]": {
        "wildtype": "S",
        "resistant": {"N"}
    },

    "dhps_437[G]": {
        "wildtype": "A",
        "resistant": {"G"}
    }
}

In [ ]:
# known columns
known_marker = {**marker_info,**associated_marker }
known_encoder = []

for col, item in known_marker.items():
    known_encoder.append(col)

In [ ]:
def classify_known_marker(value, wildtype, resistance_alleles):

    if pd.isna(value):
        return "Missing"

    value = str(value).strip()

    if value in {".", "-", "*", "!"}:
        return "Missing"

    if "," in value:

        haps = [x.strip().upper() for x in value.split(",")]

        if any(x in {"", "-", "*", "!"} for x in haps):
            return "Missing"

        if any(x in resistance_alleles for x in haps):
            return "Resistant"

        if all(x == wildtype.upper() for x in haps):
            return "Sensitive"

        return "Missing"

    allele = value.upper()

    if allele in resistance_alleles:
        return "Resistant"

    if allele == wildtype.upper():
        return "Sensitive"

    return "Missing"

In [ ]:
# handle mutations causing drug resistance
for column, info in marker_info.items():

    encoded[column] = genotype[column].apply(
        lambda x: classify_known_marker(
            x,
            wildtype=info["wildtype"],
            resistance_alleles=info["resistant"]
        )
    )

In [ ]:
# handle mutations associated with resistance
for column, info in associated_marker.items():
    new_column = f"{column}_assoc"
    encoded[new_column] = genotype[column].apply(
        lambda x: classify_known_marker(
            x,
            wildtype=info["wildtype"],
            resistance_alleles=info["resistant"]
        )
    )

In [ ]:
encoded.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive

#### Handling kelch13

In [ ]:
kelch13_col = "kelch13_349-726_ns_changes"

In [ ]:
k13_resistance = {
    "F446I",
    "N458Y",
    "C469Y",
    "M476I",
    "Y493H",
    "R539T",
    "I543T",
    "P553L",
    "R561H",
    "P574L",
    "C580Y",
    "R622I",
    "A675V"
}

In [ ]:
# classifying k13
def classify_k13(value):

    if pd.isna(value):
        return "Missing"

    value = str(value).strip()

    if value in {"", ".", "-", "*", "!"}:
        return "Missing"

    # Some cells may contain multiple mutations
    mutations = [
        x.strip().upper()
        for x in value.split(",")
    ]

    if any(m in k13_resistance for m in mutations):
        return "Resistant"

    return "Other"

In [ ]:
encoded["kelch13_known"] = genotype[
    "kelch13_349-726_ns_changes"
].apply(classify_k13)

In [ ]:
encoded.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,kelch13_known
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing

#### Handling resistance due to multiple column copy

In [ ]:
# encoding if multiple copies associated with drug resistance
def copy_encoder(value):

    # Missing
    if pd.isna(value) or str(value).strip() == "":
        return "Missing"

    value = str(value).strip()

    # ---------- Special: copy number ----------
    # ----- Special: copy number ----------
    
    if int(value) == 0:
        return "Sensitive"
    elif int(value) == 1:
        return "Resistant"
    elif value in {"-", "*", "!"}:
        return "missing"
    else:

        return "rare"

In [ ]:
encoded[["mdr1_dup_call", "pm2_dup_call"]] = genotype[["mdr1_dup_call", "pm2_dup_call"]].map(copy_encoder)

In [ ]:
encoded.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,kelch13_known,mdr1_dup_call,pm2_dup_call
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive

In [ ]:
encoded.to_csv('Important_genotype.csv',index = True)

## Handling other columns

In [ ]:
genotype_col = genotype.columns.to_list()
#known_marker.append(["mdr1_dup_call", "pm2_dup_call","kelch13_349-726_ns_changes"])
len(genotype_col)
genotype_col

['Sample',
 'crt_72[C]',
 'crt_74[M]',
 'crt_75[N]',
 'crt_76[K]',
 'crt_72-76[CVMNK]',
 'crt_93[T]',
 'crt_97[H]',
 'crt_218[I]',
 'crt_220[A]',
 'crt_271[Q]',
 'crt_326[N]',
 'crt_333[T]',
 'crt_353[G]',
 'crt_356[I]',
 'crt_371[R]',
 'dhfr_16[N]',
 'dhfr_51[N]',
 'dhfr_59[C]',
 'dhfr_108[S]',
 'dhfr_164[I]',
 'dhfr_306[S]',
 'dhps_436[S]',
 'dhps_437[G]',
 'dhps_540[K]',
 'dhps_581[A]',
 'dhps_613[A]',
 'exo_415[E]',
 'mdr1_86[N]',
 'mdr1_184[Y]',
 'mdr1_1034[S]',
 'mdr1_1042[N]',
 'mdr1_1226[F]',
 'mdr1_1246[D]',
 'arps10_127-128[VD]',
 'fd_193[D]',
 'mdr2_484[T]',
 'kelch13_349-726_ns_changes',
 'mdr1_dup_call',
 'pm2_dup_call']

In [ ]:
rare_col = [
    col for col in genotype.columns
    if col not in known_marker
    and col != "Sample"
]

In [ ]:
exclude = {
    "Sample",
    "crt_72-76[CVMNK]",
    "kelch13_349-726_ns_changes",
    "mdr1_dup_call",
    "pm2_dup_call"
}

rare_col = [
    col for col in genotype.columns
    if col not in known_marker
    and col not in exclude
]

print(rare_col)

['crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]', 'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]', 'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_306[S]', 'dhps_436[S]', 'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]', 'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]', 'fd_193[D]', 'mdr2_484[T]']

### Handling rare mutations

In [ ]:
# extracting rfference ammino acide for rare columns
import re

rare_ref = {}

for col in rare_col:
    match = re.search(r'\[([A-Z]+)\]', col)
    
    if match:
        rare_ref[col] = match.group(1)

print(rare_ref)

{'crt_72[C]': 'C', 'crt_74[M]': 'M', 'crt_75[N]': 'N', 'crt_93[T]': 'T', 'crt_97[H]': 'H', 'crt_218[I]': 'I', 'crt_220[A]': 'A', 'crt_271[Q]': 'Q', 'crt_326[N]': 'N', 'crt_333[T]': 'T', 'crt_353[G]': 'G', 'crt_356[I]': 'I', 'crt_371[R]': 'R', 'dhfr_16[N]': 'N', 'dhfr_306[S]': 'S', 'dhps_436[S]': 'S', 'exo_415[E]': 'E', 'mdr1_86[N]': 'N', 'mdr1_184[Y]': 'Y', 'mdr1_1034[S]': 'S', 'mdr1_1042[N]': 'N', 'mdr1_1226[F]': 'F', 'mdr1_1246[D]': 'D', 'arps10_127-128[VD]': 'VD', 'fd_193[D]': 'D', 'mdr2_484[T]': 'T'}

In [ ]:
# encoding rare (undetermined column)
def encode_rare(value, ref):
    
    # Missing value
    if pd.isna(value):
        return "Missing"
    
    value = str(value).strip()
    
    # Missing/uncertain symbols
    if value == "" or any(x in value for x in ["*", "!", "."]):
        return "Missing"
    
    # Split heterozygous calls
    alleles = [x.strip() for x in value.split(",")]
    
    # If ALL observed alleles are reference
    if all(allele == ref for allele in alleles):
        return "sensitive"
    
    # Any non-reference mutation
    return "Rare"

In [ ]:


for col in rare_col:
    
    ref = rare_ref[col]
    
    encoded[col] = genotype[col].apply(
        lambda x: encode_rare(x, ref)
    )

In [ ]:
encoded

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,...,exo_415[E],mdr1_86[N],mdr1_184[Y],mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T]
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,Rare,Rare,sensitive,sensitive,sensitive,Rare,sensitive,sensitive,sensitive
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,Rare,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,Rare,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24404,SPT92049,Sensitive,Resistant,Missing,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,Rare,sensitive,sensitive,sensitive
24405,SPT92054,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
24406,SPT92057,Sensitive,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive
24407,SPT94772,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,Rare,Rare,Rare,Rare,Rare,sensitive,sensitive,Rare
24408,SPT94773,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive

In [ ]:
encoded.shape

(24409, 39)

# Handling the drug phenotype

In [ ]:
# loading sample metadata
metadata = pd.read_csv("../data/raw/Pf8-samples.csv")

In [ ]:
metadata.columns

Index(['sample_id', 'year', 'qc_pass', 'study_id', 'region', 'country',
       'country_id', 'site', 'site_id', 'ARTresistant', 'CQresistant',
       'MQresistant', 'PPQresistant', 'PYRresistant', 'SDXresistant'],
      dtype='str')

In [ ]:
# dropping unnecessary columns
del_col = ['year', 'qc_pass', 'study_id', 'region', 'country', 'country_id', 'site', 'site_id']

In [ ]:
merged_encoded = encoded.merge(metadata, left_on = 'Sample', right_on = 'sample_id', how = 'left')

In [ ]:
merged_encoded.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,...,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [ ]:
merged_encoded.shape

(24409, 54)

In [ ]:
# removing unnecessary columns 
merged_encoded.drop(columns = del_col, inplace = True)

In [ ]:
merged_encoded.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,...,arps10_127-128[VD],fd_193[D],mdr2_484[T],sample_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,FP0008-C,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,FP0009-C,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,FP0010-CW,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,FP0011-CW,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,FP0012-CW,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [ ]:
merged_encoded.info()

<class 'pandas.DataFrame'>
RangeIndex: 24409 entries, 0 to 24408
Data columns (total 46 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sample              24409 non-null  str
 1   crt_76[K]           24409 non-null  str
 2   dhfr_108[S]         24409 non-null  str
 3   dhps_437[G]         24409 non-null  str
 4   dhfr_51[N]_assoc    24409 non-null  str
 5   dhfr_59[C]_assoc    24409 non-null  str
 6   dhfr_164[I]_assoc   24409 non-null  str
 7   dhps_540[K]_assoc   24409 non-null  str
 8   dhps_581[A]_assoc   24409 non-null  str
 9   dhps_613[A]_assoc   24409 non-null  str
 10  kelch13_known       24409 non-null  str
 11  mdr1_dup_call       24409 non-null  str
 12  pm2_dup_call        24409 non-null  str
 13  crt_72[C]           24409 non-null  str
 14  crt_74[M]           24409 non-null  str
 15  crt_75[N]           24409 non-null  str
 16  crt_93[T]           24409 non-null  str
 17  crt_97[H]           24409 non-null  str
 18  crt_218[I]          24409 non-null  str
 19  crt_220[A]          24409 non-null  str
 20  crt_271[Q]          24409 non-null  str
 21  crt_326[N]          24409 non-null  str
 22  crt_333[T]          24409 non-null  str
 23  crt_353[G]          24409 non-null  str
 24  crt_356[I]          24409 non-null  str
 25  crt_371[R]          24409 non-null  str
 26  dhfr_16[N]          24409 non-null  str
 27  dhfr_306[S]         24409 non-null  str
 28  dhps_436[S]         24409 non-null  str
 29  exo_415[E]          24409 non-null  str
 30  mdr1_86[N]          24409 non-null  str
 31  mdr1_184[Y]         24409 non-null  str
 32  mdr1_1034[S]        24409 non-null  str
 33  mdr1_1042[N]        24409 non-null  str
 34  mdr1_1226[F]        24409 non-null  str
 35  mdr1_1246[D]        24409 non-null  str
 36  arps10_127-128[VD]  24409 non-null  str
 37  fd_193[D]           24409 non-null  str
 38  mdr2_484[T]         24409 non-null  str
 39  sample_id           24409 non-null  str
 40  ARTresistant        24409 non-null  str
 41  CQresistant         24409 non-null  str
 42  MQresistant         24409 non-null  str
 43  PPQresistant        24409 non-null  str
 44  PYRresistant        24409 non-null  str
 45  SDXresistant        24409 non-null  str
dtypes: str(46)
memory usage: 8.6 MB

## Handling target columns

In [ ]:
target_df = merged_encoded[['ARTresistant', 'CQresistant',
       'MQresistant', 'PPQresistant', 'PYRresistant', 'SDXresistant']]

In [ ]:
target_col = ['ARTresistant', 'CQresistant','MQresistant', 'PPQresistant', 'PYRresistant', 'SDXresistant']

In [ ]:
pd.set_option('display.max_rows', None)
for col in target_df.columns:
    print(f"\n{col}")
    print(target_df[col].value_counts(dropna=False))

ARTresistant
ARTresistant
sensitive       17147
resistant        3905
undetermined     3357
Name: count, dtype: int64

CQresistant
CQresistant
resistant       12432
sensitive       10768
undetermined     1209
Name: count, dtype: int64

MQresistant
MQresistant
sensitive       12598
undetermined    11153
resistant         658
Name: count, dtype: int64

PPQresistant
PPQresistant
sensitive       13467
undetermined    10454
resistant         488
Name: count, dtype: int64

PYRresistant
PYRresistant
resistant       21964
undetermined     1230
sensitive        1215
Name: count, dtype: int64

SDXresistant
SDXresistant
resistant       19270
sensitive        3601
undetermined     1538
Name: count, dtype: int64

### Encoding the y_target column

In [ ]:
import numpy as np

y = merged_encoded[target_col].replace({
    "sensitive": 0,
    "resistant": 1,
    "undetermined": 0
})

In [ ]:
y.head()

  ARTresistant CQresistant MQresistant PPQresistant PYRresistant SDXresistant
0            0           0           0            0            0            0
1            0           1           0            0            1            0
2            0           0           0            0            1            1
3            0           0           0            0            1            0
4            0           1           0            0            1            0

## Encoding features variable

In [ ]:
features_df = merged_encoded.drop(columns = target_col)

In [ ]:
features_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24409 entries, 0 to 24408
Data columns (total 40 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Sample              24409 non-null  str
 1   crt_76[K]           24409 non-null  str
 2   dhfr_108[S]         24409 non-null  str
 3   dhps_437[G]         24409 non-null  str
 4   dhfr_51[N]_assoc    24409 non-null  str
 5   dhfr_59[C]_assoc    24409 non-null  str
 6   dhfr_164[I]_assoc   24409 non-null  str
 7   dhps_540[K]_assoc   24409 non-null  str
 8   dhps_581[A]_assoc   24409 non-null  str
 9   dhps_613[A]_assoc   24409 non-null  str
 10  kelch13_known       24409 non-null  str
 11  mdr1_dup_call       24409 non-null  str
 12  pm2_dup_call        24409 non-null  str
 13  crt_72[C]           24409 non-null  str
 14  crt_74[M]           24409 non-null  str
 15  crt_75[N]           24409 non-null  str
 16  crt_93[T]           24409 non-null  str
 17  crt_97[H]           24409 non-null  str
 18  crt_218[I]          24409 non-null  str
 19  crt_220[A]          24409 non-null  str
 20  crt_271[Q]          24409 non-null  str
 21  crt_326[N]          24409 non-null  str
 22  crt_333[T]          24409 non-null  str
 23  crt_353[G]          24409 non-null  str
 24  crt_356[I]          24409 non-null  str
 25  crt_371[R]          24409 non-null  str
 26  dhfr_16[N]          24409 non-null  str
 27  dhfr_306[S]         24409 non-null  str
 28  dhps_436[S]         24409 non-null  str
 29  exo_415[E]          24409 non-null  str
 30  mdr1_86[N]          24409 non-null  str
 31  mdr1_184[Y]         24409 non-null  str
 32  mdr1_1034[S]        24409 non-null  str
 33  mdr1_1042[N]        24409 non-null  str
 34  mdr1_1226[F]        24409 non-null  str
 35  mdr1_1246[D]        24409 non-null  str
 36  arps10_127-128[VD]  24409 non-null  str
 37  fd_193[D]           24409 non-null  str
 38  mdr2_484[T]         24409 non-null  str
 39  sample_id           24409 non-null  str
dtypes: str(40)
memory usage: 7.4 MB

In [ ]:
features_df.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,...,mdr1_86[N],mdr1_184[Y],mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],sample_id
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,FP0008-C
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,Rare,sensitive,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,FP0009-C
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,FP0010-CW
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,FP0011-CW
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,FP0012-CW

In [ ]:
features_df = features_df.drop(
    columns=["Sample", "sample_id"],
    errors="ignore"
).copy()

In [ ]:
for col in features_df.columns:
    print(f"\n===== {col} =====")
    print(features_df[col].value_counts(dropna=False))

===== crt_76[K] =====
crt_76[K]
Resistant    13593
Sensitive    10768
Missing         48
Name: count, dtype: int64

===== dhfr_108[S] =====
dhfr_108[S]
Resistant    22780
Sensitive     1215
Missing        414
Name: count, dtype: int64

===== dhps_437[G] =====
dhps_437[G]
Resistant    20538
Sensitive     3601
Missing        270
Name: count, dtype: int64

===== dhfr_51[N]_assoc =====
dhfr_51[N]_assoc
Resistant    20083
Sensitive     4029
Missing        297
Name: count, dtype: int64

===== dhfr_59[C]_assoc =====
dhfr_59[C]_assoc
Resistant    22051
Sensitive     2034
Missing        323
Other            1
Name: count, dtype: int64

===== dhfr_164[I]_assoc =====
dhfr_164[I]_assoc
Sensitive    19106
Resistant     5032
Missing        269
Other            2
Name: count, dtype: int64

===== dhps_540[K]_assoc =====
dhps_540[K]_assoc
Sensitive    12850
Resistant     8386
Other         2810
Missing        363
Name: count, dtype: int64

===== dhps_581[A]_assoc =====
dhps_581[A]_assoc
Sensitive    18695
Resistant     5349
Missing        365
Name: count, dtype: int64

===== dhps_613[A]_assoc =====
dhps_613[A]_assoc
Sensitive    22744
Resistant     1359
Missing        305
Other            1
Name: count, dtype: int64

===== kelch13_known =====
kelch13_known
Missing      19945
Resistant     3802
Other          662
Name: count, dtype: int64

===== mdr1_dup_call =====
mdr1_dup_call
Sensitive    19512
rare          4195
Resistant      702
Name: count, dtype: int64

===== pm2_dup_call =====
pm2_dup_call
Sensitive    17610
rare          4719
Resistant     2080
Name: count, dtype: int64

===== crt_72[C] =====
crt_72[C]
sensitive    23955
Rare           454
Name: count, dtype: int64

===== crt_74[M] =====
crt_74[M]
Rare         13091
sensitive    11318
Name: count, dtype: int64

===== crt_75[N] =====
crt_75[N]
Rare         13198
sensitive    11205
Missing          6
Name: count, dtype: int64

===== crt_93[T] =====
crt_93[T]
sensitive    23302
Rare          1107
Name: count, dtype: int64

===== crt_97[H] =====
crt_97[H]
sensitive    23958
Rare           451
Name: count, dtype: int64

===== crt_218[I] =====
crt_218[I]
sensitive    23087
Rare          1322
Name: count, dtype: int64

===== crt_220[A] =====
crt_220[A]
Rare         13791
sensitive    10618
Name: count, dtype: int64

===== crt_271[Q] =====
crt_271[Q]
Rare         13120
sensitive    11289
Name: count, dtype: int64

===== crt_326[N] =====
crt_326[N]
sensitive    17557
Rare          6852
Name: count, dtype: int64

===== crt_333[T] =====
crt_333[T]
sensitive    22954
Rare          1453
Missing          2
Name: count, dtype: int64

===== crt_353[G] =====
crt_353[G]
sensitive    24279
Rare           130
Name: count, dtype: int64

===== crt_356[I] =====
crt_356[I]
sensitive    14846
Rare          9563
Name: count, dtype: int64

===== crt_371[R] =====
crt_371[R]
Rare         12455
sensitive    11954
Name: count, dtype: int64

===== dhfr_16[N] =====
dhfr_16[N]
Rare    24409
Name: count, dtype: int64

===== dhfr_306[S] =====
dhfr_306[S]
sensitive    23882
Rare           527
Name: count, dtype: int64

===== dhps_436[S] =====
dhps_436[S]
sensitive    16150
Rare          8248
Missing         11
Name: count, dtype: int64

===== exo_415[E] =====
exo_415[E]
sensitive    21720
Rare          2689
Name: count, dtype: int64

===== mdr1_86[N] =====
mdr1_86[N]
sensitive    21140
Rare          3269
Name: count, dtype: int64

===== mdr1_184[Y] =====
mdr1_184[Y]
Rare         13882
sensitive    10527
Name: count, dtype: int64

===== mdr1_1034[S] =====
mdr1_1034[S]
sensitive    23123
Rare          1286
Name: count, dtype: int64

===== mdr1_1042[N] =====
mdr1_1042[N]
sensitive    22940
Rare          1469
Name: count, dtype: int64

===== mdr1_1226[F] =====
mdr1_1226[F]
sensitive    22628
Rare          1781
Name: count, dtype: int64

===== mdr1_1246[D] =====
mdr1_1246[D]
sensitive    22711
Rare          1698
Name: count, dtype: int64

===== arps10_127-128[VD] =====
arps10_127-128[VD]
sensitive    19165
Rare          5229
Missing         15
Name: count, dtype: int64

===== fd_193[D] =====
fd_193[D]
sensitive    18937
Rare          5472
Name: count, dtype: int64

===== mdr2_484[T] =====
mdr2_484[T]
sensitive    18642
Rare          5767
Name: count, dtype: int64

In [ ]:
features_df = features_df[
    features_df['dhps_613[A]_assoc'] != "Other"
].copy()

In [ ]:
for col in features_df.columns:
    print(f"\n===== {col} =====")
    print(features_df[col].value_counts(dropna=False))

===== crt_76[K] =====
crt_76[K]
Resistant    13593
Sensitive    10767
Missing         48
Name: count, dtype: int64

===== dhfr_108[S] =====
dhfr_108[S]
Resistant    22779
Sensitive     1215
Missing        414
Name: count, dtype: int64

===== dhps_437[G] =====
dhps_437[G]
Resistant    20538
Sensitive     3600
Missing        270
Name: count, dtype: int64

===== dhfr_51[N]_assoc =====
dhfr_51[N]_assoc
Resistant    20082
Sensitive     4029
Missing        297
Name: count, dtype: int64

===== dhfr_59[C]_assoc =====
dhfr_59[C]_assoc
Resistant    22050
Sensitive     2034
Missing        323
Other            1
Name: count, dtype: int64

===== dhfr_164[I]_assoc =====
dhfr_164[I]_assoc
Sensitive    19105
Resistant     5032
Missing        269
Other            2
Name: count, dtype: int64

===== dhps_540[K]_assoc =====
dhps_540[K]_assoc
Sensitive    12849
Resistant     8386
Other         2810
Missing        363
Name: count, dtype: int64

===== dhps_581[A]_assoc =====
dhps_581[A]_assoc
Sensitive    18694
Resistant     5349
Missing        365
Name: count, dtype: int64

===== dhps_613[A]_assoc =====
dhps_613[A]_assoc
Sensitive    22744
Resistant     1359
Missing        305
Name: count, dtype: int64

===== kelch13_known =====
kelch13_known
Missing      19944
Resistant     3802
Other          662
Name: count, dtype: int64

===== mdr1_dup_call =====
mdr1_dup_call
Sensitive    19511
rare          4195
Resistant      702
Name: count, dtype: int64

===== pm2_dup_call =====
pm2_dup_call
Sensitive    17610
rare          4718
Resistant     2080
Name: count, dtype: int64

===== crt_72[C] =====
crt_72[C]
sensitive    23954
Rare           454
Name: count, dtype: int64

===== crt_74[M] =====
crt_74[M]
Rare         13091
sensitive    11317
Name: count, dtype: int64

===== crt_75[N] =====
crt_75[N]
Rare         13198
sensitive    11204
Missing          6
Name: count, dtype: int64

===== crt_93[T] =====
crt_93[T]
sensitive    23301
Rare          1107
Name: count, dtype: int64

===== crt_97[H] =====
crt_97[H]
sensitive    23957
Rare           451
Name: count, dtype: int64

===== crt_218[I] =====
crt_218[I]
sensitive    23086
Rare          1322
Name: count, dtype: int64

===== crt_220[A] =====
crt_220[A]
Rare         13791
sensitive    10617
Name: count, dtype: int64

===== crt_271[Q] =====
crt_271[Q]
Rare         13120
sensitive    11288
Name: count, dtype: int64

===== crt_326[N] =====
crt_326[N]
sensitive    17556
Rare          6852
Name: count, dtype: int64

===== crt_333[T] =====
crt_333[T]
sensitive    22953
Rare          1453
Missing          2
Name: count, dtype: int64

===== crt_353[G] =====
crt_353[G]
sensitive    24278
Rare           130
Name: count, dtype: int64

===== crt_356[I] =====
crt_356[I]
sensitive    14845
Rare          9563
Name: count, dtype: int64

===== crt_371[R] =====
crt_371[R]
Rare         12455
sensitive    11953
Name: count, dtype: int64

===== dhfr_16[N] =====
dhfr_16[N]
Rare    24408
Name: count, dtype: int64

===== dhfr_306[S] =====
dhfr_306[S]
sensitive    23881
Rare           527
Name: count, dtype: int64

===== dhps_436[S] =====
dhps_436[S]
sensitive    16149
Rare          8248
Missing         11
Name: count, dtype: int64

===== exo_415[E] =====
exo_415[E]
sensitive    21719
Rare          2689
Name: count, dtype: int64

===== mdr1_86[N] =====
mdr1_86[N]
sensitive    21139
Rare          3269
Name: count, dtype: int64

===== mdr1_184[Y] =====
mdr1_184[Y]
Rare         13881
sensitive    10527
Name: count, dtype: int64

===== mdr1_1034[S] =====
mdr1_1034[S]
sensitive    23122
Rare          1286
Name: count, dtype: int64

===== mdr1_1042[N] =====
mdr1_1042[N]
sensitive    22939
Rare          1469
Name: count, dtype: int64

===== mdr1_1226[F] =====
mdr1_1226[F]
sensitive    22627
Rare          1781
Name: count, dtype: int64

===== mdr1_1246[D] =====
mdr1_1246[D]
sensitive    22710
Rare          1698
Name: count, dtype: int64

===== arps10_127-128[VD] =====
arps10_127-128[VD]
sensitive    19164
Rare          5229
Missing         15
Name: count, dtype: int64

===== fd_193[D] =====
fd_193[D]
sensitive    18936
Rare          5472
Name: count, dtype: int64

===== mdr2_484[T] =====
mdr2_484[T]
sensitive    18641
Rare          5767
Name: count, dtype: int64

In [ ]:
features_df['crt_371[R]'].value_counts()

crt_371[R]
Rare         12455
sensitive    11953
Name: count, dtype: int64

### Encoding the X features

In [ ]:
# defining different columns 
known_cols = list(marker_info.keys())
known_cols.append("mdr1_dup_call")
known_cols.append("pm2_dup_call")


associated_cols = list(associated_marker.keys())

rare_cols = rare_col

In [ ]:
print("Known:", known_cols)
print("Associated:", associated_cols)
print("Rare:", rare_cols)

Known: ['crt_76[K]', 'dhfr_108[S]', 'dhps_437[G]', 'mdr1_dup_call', 'pm2_dup_call']
Associated: ['dhfr_51[N]', 'dhfr_59[C]', 'dhfr_164[I]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]']
Rare: ['crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]', 'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]', 'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_306[S]', 'dhps_436[S]', 'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]', 'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]', 'fd_193[D]', 'mdr2_484[T]']

In [ ]:
print([c for c in features_df.columns if 'dhfr' in c or 'dhps' in c])

['dhfr_108[S]', 'dhps_437[G]', 'dhfr_51[N]_assoc', 'dhfr_59[C]_assoc', 'dhfr_164[I]_assoc', 'dhps_540[K]_assoc', 'dhps_581[A]_assoc', 'dhps_613[A]_assoc', 'dhfr_16[N]', 'dhfr_306[S]', 'dhps_436[S]']

In [ ]:
assoc_col = [c for c in encoded.columns if '_assoc' in c]

In [ ]:
# encoding known and associated columns

X_known = features_df[known_cols].replace({
    "Resistant": 10,
    "Sensitive": 2,
    "sensitive": 2,
    "Missing": 0,
    "rare": 3
})

X_associated = features_df[assoc_col].replace({
    "Resistant": 5,
    "Sensitive": 2,
    "sensitive": 2,
    "Missing": 0,
    "rare": 3
})

In [ ]:
# viewing columns associated with known resistance
for col in known_cols:
    print(col, X_known[col].value_counts(dropna=False))

crt_76[K] crt_76[K]
10    13593
2     10767
0        48
Name: count, dtype: int64
dhfr_108[S] dhfr_108[S]
10    22779
2      1215
0       414
Name: count, dtype: int64
dhps_437[G] dhps_437[G]
10    20538
2      3600
0       270
Name: count, dtype: int64
mdr1_dup_call mdr1_dup_call
2     19511
3      4195
10      702
Name: count, dtype: int64
pm2_dup_call pm2_dup_call
2     17610
3      4718
10     2080
Name: count, dtype: int64

In [ ]:
# viewing columns assocciated with resistance associations
for col in assoc_col:
    print(col, X_associated[col].value_counts(dropna=False))

dhfr_51[N]_assoc dhfr_51[N]_assoc
5    20082
2     4029
0      297
Name: count, dtype: int64
dhfr_59[C]_assoc dhfr_59[C]_assoc
5        22050
2         2034
0          323
Other        1
Name: count, dtype: int64
dhfr_164[I]_assoc dhfr_164[I]_assoc
2        19105
5         5032
0          269
Other        2
Name: count, dtype: int64
dhps_540[K]_assoc dhps_540[K]_assoc
2        12849
5         8386
Other     2810
0          363
Name: count, dtype: int64
dhps_581[A]_assoc dhps_581[A]_assoc
2    18694
5     5349
0      365
Name: count, dtype: int64
dhps_613[A]_assoc dhps_613[A]_assoc
2    22744
5     1359
0      305
Name: count, dtype: int64

In [ ]:
# Handling rare mutations
X_rare = features_df[rare_cols].replace({
    "sensitive": 0,
    "Sensitive": 0,
    "Rare": 1,
    "Missing": np.nan
})

## Haplotypes associated with drug resistance

In [ ]:
# columns for mutations in Sulfadoxine-Pyrimethamine (treatment) and Sulfadoxine-Pyrimethamine (IPTp)
dhfr_cols = [
    "dhfr_51[N]",
    "dhfr_59[C]",
    "dhfr_108[S]",
    "dhfr_164[I]"
]

dhps_cols = [
    "dhps_437[G]",
    "dhps_540[K]",
    "dhps_581[A]",
    "dhps_613[A]"
]

combo_cols = dhfr_cols + dhps_cols

In [ ]:
# dealing with SP-IPTp (sextuple mutant)
def classify_sp(row):

    cols = [
        "dhfr_51[N]",
        "dhfr_59[C]",
        "dhfr_108[S]",
        "dhfr_164[I]",
        "dhps_437[G]",
        "dhps_540[K]",
        "dhps_581[A]",
        "dhps_613[A]"
    ]

    if any(is_ambiguous(row[c]) for c in cols):
        return "Rare"

    if (
        row["dhfr_51[N]"] == "I"
        and row["dhfr_59[C]"] == "R"
        and row["dhfr_108[S]"] == "N"
        and row["dhps_437[G]"] == "G"
        and row["dhps_540[K]"] == "E"
        and (
            row["dhfr_164[I]"] == "L"
            or row["dhps_581[A]"] == "G"
            or row["dhps_613[A]"] in {"S", "T"}
        )
    ):
        return "Resistant"

    return "Sensitive"

In [ ]:
# helper function
def is_ambiguous(value):

    if pd.isna(value):
        return True

    value = str(value).strip()

    if value in {"-", "*", "!"}:
        return True

    return value.islower()

In [ ]:
# dealing with Pyrimethamine (triple mutant)
def classify_pyr(row):

    cols = [
        "dhfr_51[N]",
        "dhfr_59[C]",
        "dhfr_108[S]"
    ]

    if any(is_ambiguous(row[c]) for c in cols):
        return "Rare"

    if (
        row["dhfr_51[N]"] == "I"
        and row["dhfr_59[C]"] == "R"
        and row["dhfr_108[S]"] == "N"
    ):
        return "Resistant"

    return "Sensitive"

In [ ]:
# pyresistant is for triplet Pyrimethamine
encoded["PYRresistant"] = genotype.apply(classify_pyr, axis=1)
# Spresistant if for sextuple mutant
encoded["SPresistant"] = genotype.apply(classify_sp, axis=1)

In [ ]:
encoded.head()

,Sample,crt_76[K],dhfr_108[S],dhps_437[G],dhfr_51[N]_assoc,dhfr_59[C]_assoc,dhfr_164[I]_assoc,dhps_540[K]_assoc,dhps_581[A]_assoc,dhps_613[A]_assoc,...,mdr1_184[Y],mdr1_1034[S],mdr1_1042[N],mdr1_1226[F],mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],PYRresistant,SPresistant
0,FP0008-C,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,Sensitive,Sensitive
1,FP0009-C,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,sensitive,sensitive,sensitive,Rare,sensitive,sensitive,sensitive,Resistant,Sensitive
2,FP0010-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,Resistant,Sensitive
3,FP0011-CW,Resistant,Resistant,Resistant,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Rare,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,Resistant,Sensitive
4,FP0012-CW,Resistant,Resistant,Sensitive,Resistant,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,sensitive,Resistant,Sensitive

In [ ]:
def encode(value, column):

    # Missing
    if pd.isna(value) or str(value).strip() == "":
        return "Missing"

    value = str(value).strip()

    # ---------- Special: copy number ----------
    # ----- Special: copy number ----------
    if column in ["mdr1_dup_call", "pm2_dup_call"]:
        if int(value) == 0:
            return "Sensitive"
        elif int(value) == 1:
            return "Resistant"
        elif int(value) in {"-", "*", "!"}:
            return "missing"
        else:
            return "rare"
    

    # ---------- Special: crt haplotype ----------
    if column == "crt_72-76[CVMNK]":

        haps = [x.strip() for x in value.split(",")]

        if any(h in {"CVIET", "SVMNT"} for h in haps):
            return "Resistant"

        if all(h == "CVMNK" for h in haps):
            return "Sensitive"

        return "Rare"

    # ---------- Special: kelch13 ----------
    if column == "kelch13_349-726_ns_changes":

        # Missing or unresolved
        if pd.isna(value):
            return "missing"

        value = str(value).strip()

        if value in {"-", "*", "!"}:
            return "missing"

        # Two haplotypes
        if "," in value:
            haps = [x.strip() for x in value.split(",")]

            # Same mutation on both haplotypes
            if len(set(haps)) == 1:
                value = haps[0]
            else:
                return "Rare"

        # Lowercase = heterozygous
        if value.islower():
            return "Rare"

        value = value.upper()

        # Wild type (if present in your data)
        if value in {"WT", "578S"}:
            return "Sensitive"

        # WHO resistance mutation
        if value in WHO_K13:
            return "Resistant"

        # Any other homozygous mutation
        return "Sensitive"
    
    

    # ---------- Multiple alleles ----------
    alleles = [a.strip() for a in value.split(",")]
    if len(alleles) > 1:

        if column in SPECIAL:
            if any(a in SPECIAL[column] for a in alleles):
                return "Resistant"
            return "Rare"

        # General columns
        if ref_aa[column] in alleles:
            return "Sensitive"

        return "Rare"

    # ---------- Single allele ----------

    allele = alleles[0]

    if column in SPECIAL:
        if allele in SPECIAL[column]:
            return "rare"

    if allele == ref_aa[column]:
        return "Sensitive"

    return "missing"

### Handling artesunate_mefloquine

In [ ]:
def classify_artesunate_mefloquine(row):

    art = row["kelch13_349-726_ns_changes"]
    mq = row["mdr1_dup_call"]

    # Missing
    if art == "Missing" or mq == "Missing":
        return "Missing"

    # Both resistant
    if art == "Resistant" and mq == "Resistant":
        return "Resistant"

    # At least one sensitive
    if art == "Sensitive" or mq == "Sensitive":
        return "Sensitive"

    # Rare/unknown combinations
    return "Rare"

In [ ]:
encoded["ASMQresistant"] = encoded.apply(
    classify_artesunate_mefloquine,
    axis=1
)

KeyError: 'kelch13_349-726_ns_changes'

### Handling piperaquine

In [ ]:
encoded.columns

Index(['Sample', 'crt_72[C]', 'crt_74[M]', 'crt_75[N]', 'crt_76[K]',
       'crt_72-76[CVMNK]', 'crt_93[T]', 'crt_97[H]', 'crt_218[I]',
       'crt_220[A]', 'crt_271[Q]', 'crt_326[N]', 'crt_333[T]', 'crt_353[G]',
       'crt_356[I]', 'crt_371[R]', 'dhfr_16[N]', 'dhfr_51[N]', 'dhfr_59[C]',
       'dhfr_108[S]', 'dhfr_164[I]', 'dhfr_306[S]', 'dhps_436[S]',
       'dhps_437[G]', 'dhps_540[K]', 'dhps_581[A]', 'dhps_613[A]',
       'exo_415[E]', 'mdr1_86[N]', 'mdr1_184[Y]', 'mdr1_1034[S]',
       'mdr1_1042[N]', 'mdr1_1226[F]', 'mdr1_1246[D]', 'arps10_127-128[VD]',
       'fd_193[D]', 'mdr2_484[T]', 'kelch13_349-726_ns_changes',
       'mdr1_dup_call', 'pm2_dup_call', 'PYRresistant', 'SPresistant',
       'ASMQresistant'],
      dtype='str')

In [ ]:
def classify_artesunate_mefloquine(row):

    art = row["kelch13_349-726_ns_changes"]
    mq = row["mdr1_dup_call"]

    # Missing
    if art == "Missing" or mq == "Missing":
        return "Missing"

    # Both resistant
    if art == "Resistant" and mq == "Resistant":
        return "Resistant"

    # At least one sensitive
    if art == "Sensitive" or mq == "Sensitive":
        return "Sensitive"

    # Rare/unknown combinations
    return "Rare"

In [ ]:
encoded

,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],...,mdr1_1246[D],arps10_127-128[VD],fd_193[D],mdr2_484[T],kelch13_349-726_ns_changes,mdr1_dup_call,pm2_dup_call,PYRresistant,SPresistant,ASMQresistant
0,FP0008-C,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive,Sensitive,Sensitive,Missing
1,FP0009-C,Sensitive,missing,missing,missing,Resistant,Sensitive,Sensitive,Sensitive,missing,...,missing,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive,Resistant,Sensitive,Missing
2,FP0010-CW,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive,Resistant,Sensitive,Missing
3,FP0011-CW,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive,Resistant,Sensitive,Missing
4,FP0012-CW,Sensitive,missing,missing,missing,Resistant,Sensitive,Sensitive,Sensitive,missing,...,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive,Resistant,Sensitive,Missing
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24404,SPT92049,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,missing,Sensitive,Sensitive,Sensitive,missing,rare,rare,Resistant,Rare,Rare
24405,SPT92054,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,rare,Resistant,Sensitive,Missing
24406,SPT92057,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,Sensitive,...,Sensitive,Sensitive,Sensitive,Sensitive,missing,rare,rare,Resistant,Sensitive,Rare
24407,SPT94772,Sensitive,missing,missing,missing,Resistant,Sensitive,Sensitive,Sensitive,missing,...,missing,Sensitive,Sensitive,missing,missing,rare,rare,Resistant,Sensitive,Rare
24408,SPT94773,Sensitive,missing,missing,missing,Resistant,Sensitive,Sensitive,Sensitive,missing,...,Sensitive,Sensitive,Sensitive,Sensitive,Missing,Sensitive,Sensitive,Resistant,Sensitive,Missing

## Filtering African countries only

,sample_id,year,qc_pass,study_id,region,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant,SDXresistant
0,FP0008-C,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,FP0009-C,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,FP0010-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,FP0011-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,FP0012-CW,2014,True,1147,NaN,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [ ]:
metadata['ARTresistant'].unique()

<StringArray>
['sensitive', nan, 'undetermined', 'resistant']
Length: 4, dtype: str

In [ ]:
metadata['ARTresistant'].value_counts()

ARTresistant
sensitive       17147
resistant        3905
undetermined     3357
Name: count, dtype: int64

In [ ]:
metadata['ARTresistant'].isna().sum()

np.int64(8586)

In [ ]:
metadata['country'].unique()

<StringArray>
[                      'Mauritania',                           'Gambia',
                           'Guinea',                            'Kenya',
                         'Thailand',                         'Tanzania',
                            'Ghana',                         'Cambodia',
                        'Indonesia',                     'Burkina Faso',
                             'Mali',                 'Papua New Guinea',
                             'Peru',                       'Bangladesh',
                           'Malawi',                          'Vietnam',
                         'Colombia',                        'Venezuela',
                           'Uganda',                          'Myanmar',
                             'Laos', 'Democratic Republic of the Congo',
                          'Nigeria',                       'Madagascar',
                         'Cameroon',                    'Côte d'Ivoire',
                         'Ethiopia',                            'Benin',
                          'Senegal',                            'Gabon',
                            'India',                            'Sudan',
                       'Mozambique',                         'Honduras']
Length: 34, dtype: str

<class 'pandas.DataFrame'>
Index: 20951 entries, 0 to 32994
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sample_id     20951 non-null  str
 1   year          20951 non-null  int64
 2   qc_pass       20951 non-null  bool
 3   study_id      20951 non-null  int64
 4   region        0 non-null      float64
 5   country       20951 non-null  str
 6   country_id    20951 non-null  str
 7   site          20951 non-null  str
 8   site_id       20951 non-null  str
 9   ARTresistant  14508 non-null  str
 10  CQresistant   14508 non-null  str
 11  MQresistant   14508 non-null  str
 12  PPQresistant  14508 non-null  str
 13  PYRresistant  14508 non-null  str
 14  SDXresistant  14508 non-null  str
dtypes: bool(1), float64(1), int64(2), str(11)
memory usage: 2.4 MB

In [ ]:
africa_df.columns

Index(['sample_id', 'year', 'qc_pass', 'study_id', 'country', 'country_id',
       'site', 'site_id', 'ARTresistant', 'CQresistant', 'MQresistant',
       'PPQresistant', 'PYRresistant', 'SDXresistant'],
      dtype='str')

In [ ]:
print(len(african_countries_geno))

20951

In [ ]:
african_countries_geno.head()

,Sample,crt_72[C],crt_74[M],crt_75[N],crt_76[K],crt_72-76[CVMNK],crt_93[T],crt_97[H],crt_218[I],crt_220[A],...,country,country_id,site,site_id,ARTresistant,CQresistant,MQresistant,PPQresistant,PYRresistant_y,SDXresistant
0,FP0008-C,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,sensitive,sensitive,undetermined,undetermined
1,FP0009-C,Sensitive,missing,missing,missing,Resistant,Sensitive,Sensitive,Sensitive,missing,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,sensitive,sensitive,resistant,sensitive
2,FP0010-CW,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,resistant
3,FP0011-CW,Sensitive,Sensitive,Sensitive,Sensitive,Resistant,Sensitive,Sensitive,Sensitive,Sensitive,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,undetermined,undetermined,undetermined,resistant,undetermined
4,FP0012-CW,Sensitive,missing,missing,missing,Resistant,Sensitive,Sensitive,Sensitive,missing,...,Mauritania,MR,Hodh el Gharbi,Hodh el Gharbi,sensitive,resistant,undetermined,undetermined,resistant,sensitive

In [ ]:
african_countries_geno.info()

<class 'pandas.DataFrame'>
RangeIndex: 20951 entries, 0 to 20950
Data columns (total 57 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Sample                      14508 non-null  str
 1   crt_72[C]                   14508 non-null  str
 2   crt_74[M]                   14508 non-null  str
 3   crt_75[N]                   14508 non-null  str
 4   crt_76[K]                   14508 non-null  str
 5   crt_72-76[CVMNK]            14508 non-null  str
 6   crt_93[T]                   14508 non-null  str
 7   crt_97[H]                   14508 non-null  str
 8   crt_218[I]                  14508 non-null  str
 9   crt_220[A]                  14508 non-null  str
 10  crt_271[Q]                  14508 non-null  str
 11  crt_326[N]                  14508 non-null  str
 12  crt_333[T]                  14508 non-null  str
 13  crt_353[G]                  14508 non-null  str
 14  crt_356[I]                  14508 non-null  str
 15  crt_371[R]                  14508 non-null  str
 16  dhfr_16[N]                  14508 non-null  str
 17  dhfr_51[N]                  14508 non-null  str
 18  dhfr_59[C]                  14508 non-null  str
 19  dhfr_108[S]                 14508 non-null  str
 20  dhfr_164[I]                 14508 non-null  str
 21  dhfr_306[S]                 14508 non-null  str
 22  dhps_436[S]                 14508 non-null  str
 23  dhps_437[G]                 14508 non-null  str
 24  dhps_540[K]                 14508 non-null  str
 25  dhps_581[A]                 14508 non-null  str
 26  dhps_613[A]                 14508 non-null  str
 27  exo_415[E]                  14508 non-null  str
 28  mdr1_86[N]                  14508 non-null  str
 29  mdr1_184[Y]                 14508 non-null  str
 30  mdr1_1034[S]                14508 non-null  str
 31  mdr1_1042[N]                14508 non-null  str
 32  mdr1_1226[F]                14508 non-null  str
 33  mdr1_1246[D]                14508 non-null  str
 34  arps10_127-128[VD]          14508 non-null  str
 35  fd_193[D]                   14508 non-null  str
 36  mdr2_484[T]                 14508 non-null  str
 37  kelch13_349-726_ns_changes  14508 non-null  str
 38  mdr1_dup_call               14508 non-null  str
 39  pm2_dup_call                14508 non-null  str
 40  PYRresistant_x              14508 non-null  str
 41  SPresistant                 14508 non-null  str
 42  ASMQresistant               14508 non-null  str
 43  sample_id                   20951 non-null  str
 44  year                        20951 non-null  int64
 45  qc_pass                     20951 non-null  bool
 46  study_id                    20951 non-null  int64
 47  country                     20951 non-null  str
 48  country_id                  20951 non-null  str
 49  site                        20951 non-null  str
 50  site_id                     20951 non-null  str
 51  ARTresistant                14508 non-null  str
 52  CQresistant                 14508 non-null  str
 53  MQresistant                 14508 non-null  str
 54  PPQresistant                14508 non-null  str
 55  PYRresistant_y              14508 non-null  str
 56  SDXresistant                14508 non-null  str
dtypes: bool(1), int64(2), str(54)
memory usage: 9.0 MB

# Merging with East African Countries

In [ ]:
# loading east africa data 
east_genotype = pd.read_csv('../processed/east-country_year2010-2019.csv')

In [ ]:
east_genotype.columns

Index(['Unnamed: 0', 'sample_id', 'year', 'qc_pass', 'study_id', 'region',
       'country', 'country_id', 'site', 'site_id', 'ARTresistant',
       'CQresistant', 'MQresistant', 'PPQresistant', 'PYRresistant',
       'SDXresistant'],
      dtype='str')

In [ ]:
# saving East africa countries encoded genotype data
east_african_geno.to_csv('../processed/East_africa_geno.csv')

# Merging with West African Countries