In [2]:
import numpy as np
import pandas as pd

In [ ]:
# loading sample metadata
samples = pd.read_csv(
    "../data/raw/original_pf8/Pf8_samples (1).txt",
    sep="\t",
    engine="python"
)

In [3]:
samples.shape

(33325, 17)

In [4]:
samples.head()

,Sample,Study,Country,Admin level 1,Country latitude,Country longitude,Admin level 1 latitude,Admin level 1 longitude,Year,ENA,All samples same case,Population,% callable,QC pass,Exclusion reason,Sample type,Sample was in Pf7
0,FP0008-C,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR1081237,FP0008-C,AF-W,82.48,True,Analysis_set,gDNA,True
1,FP0009-C,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR1081238,FP0009-C,AF-W,88.95,True,Analysis_set,gDNA,True
2,FP0010-CW,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR2889621,FP0010-CW,AF-W,87.01,True,Analysis_set,sWGA,True
3,FP0011-CW,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR2889624,FP0011-CW,AF-W,86.95,True,Analysis_set,sWGA,True
4,FP0012-CW,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR2889627,FP0012-CW,AF-W,89.86,True,Analysis_set,sWGA,True

In [ ]:
# loading the mean genotypes
dist = np.load(
    "../data/raw/original_pf8/Pf8_mean_genotype_distance_snp_only.npy",
    mmap_mode="r"
)

In [6]:
# defining africa countries
african_countries = [
    'Mauritania',
    'Gambia',
    'Guinea',
    'Kenya',
    'Tanzania',
    'Ghana',
    'Burkina Faso',
    'Mali',
    'Malawi',
    'Uganda',
    'Democratic Republic of the Congo',
    'Nigeria',
    'Madagascar',
    'Cameroon',
    "Côte d'Ivoire",
    'Ethiopia',
    'Benin',
    'Senegal',
    'Gabon',
    'Sudan',
    'Mozambique'
]

In [7]:
samples.columns

Index(['Sample', 'Study', 'Country', 'Admin level 1', 'Country latitude',
       'Country longitude', 'Admin level 1 latitude',
       'Admin level 1 longitude', 'Year', 'ENA', 'All samples same case',
       'Population', '% callable', 'QC pass', 'Exclusion reason',
       'Sample type', 'Sample was in Pf7'],
      dtype='str')

In [8]:
# filtering for africa countries that have passed qc 
filtered_samples = samples[
    (samples["QC pass"] == True ) &
    (samples["Country"].isin(african_countries))
]

print(filtered_samples.shape)
filtered_samples.head()

(14508, 17)

,Sample,Study,Country,Admin level 1,Country latitude,Country longitude,Admin level 1 latitude,Admin level 1 longitude,Year,ENA,All samples same case,Population,% callable,QC pass,Exclusion reason,Sample type,Sample was in Pf7
0,FP0008-C,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR1081237,FP0008-C,AF-W,82.48,True,Analysis_set,gDNA,True
1,FP0009-C,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR1081238,FP0009-C,AF-W,88.95,True,Analysis_set,gDNA,True
2,FP0010-CW,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR2889621,FP0010-CW,AF-W,87.01,True,Analysis_set,sWGA,True
3,FP0011-CW,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR2889624,FP0011-CW,AF-W,86.95,True,Analysis_set,sWGA,True
4,FP0012-CW,1147-PF-MR-CONWAY,Mauritania,Hodh el Gharbi,20.265149,-10.337093,16.565426,-9.832345,2014.0,ERR2889627,FP0012-CW,AF-W,89.86,True,Analysis_set,sWGA,True

In [9]:
# adding sample id to the mean distance matrix
ids = samples["Sample"].tolist()   

dist_df = pd.DataFrame(
    dist,
    index=ids,
    columns=ids
)

In [10]:
# filtered african countries id
filtered_ids = filtered_samples["Sample"].tolist()

In [11]:
# getting distance mean matrix for African countries
dist_africa = dist_df.loc[filtered_ids, filtered_ids]

In [12]:
dist_africa.shape

(14508, 14508)

In [13]:
dist_africa.to_csv('dist_africa.csv',index = True)

In [14]:
np.save("dist_africa.npy", dist_africa.to_numpy())

In [15]:
print(dist_africa.shape)

(14508, 14508)

# PCA ANALYSIS

In [16]:
dist_africa.head()

,FP0008-C,FP0009-C,FP0010-CW,FP0011-CW,FP0012-CW,FP0013-CW,FP0014-CW,FP0015-C,FP0016-C,FP0017-C,...,SPT92000,SPT92004,SPT92011,SPT92015,SPT92044,SPT92049,SPT92054,SPT92057,SPT94772,SPT94773
FP0008-C,0.000261,0.001586,0.001521,0.001513,0.001614,0.001667,0.001629,0.001574,0.001464,0.001602,...,0.001600,0.001392,0.001327,0.001382,0.001409,0.001319,0.001542,0.001425,0.001333,0.001601
FP0009-C,0.001586,0.000032,0.001537,0.001551,0.001640,0.001649,0.001676,0.001599,0.001542,0.001621,...,0.001620,0.001405,0.001371,0.001414,0.001422,0.001349,0.001533,0.001409,0.001334,0.001642
FP0010-CW,0.001521,0.001537,0.000377,0.000959,0.001569,0.001588,0.001569,0.001530,0.001498,0.001530,...,0.001559,0.001403,0.001380,0.001403,0.001455,0.001380,0.001514,0.001409,0.001355,0.001597
FP0011-CW,0.001513,0.001551,0.000959,0.000501,0.001582,0.001608,0.001565,0.001524,0.001487,0.001533,...,0.001555,0.001398,0.001391,0.001412,0.001458,0.001380,0.001514,0.001422,0.001348,0.001605
FP0012-CW,0.001614,0.001640,0.001569,0.001582,0.000030,0.001695,0.001697,0.001595,0.001569,0.001640,...,0.001628,0.001442,0.001404,0.001403,0.001471,0.001440,0.001607,0.001471,0.001380,0.001706

In [ ]:
# import required libraaries

In [4]:
from sklearn.manifold import MDS

In [5]:
import matplotlib.pyplot as plt

In [19]:
# confirm the matrix
print(dist_africa.shape)

(14508, 14508)

In [20]:
# Verify that the matrix is suittable
print(np.isnan(dist_africa.to_numpy()).sum())

0

In [21]:
# Check for infinite values
print(np.isinf(dist_africa.to_numpy()).sum())

0

In [ ]:
# Check symmetry
np.allclose(
    dist_africa,
    dist_africa.T
)

True

In [23]:
# Check the diagnol
np.diag(dist_africa)

array([2.61484063e-04, 3.22648484e-05, 3.76840006e-04, ...,
       1.07933585e-04, 2.69867087e-05, 1.60730615e-05],
      shape=(14508,), dtype=float32)

In [24]:
print(dist_africa.shape)

(14508, 14508)

Instead of writing everything from scratch, I recommend using scikit-bio.

Why?

Because it implements classical PCoA, which is the standard algorithm used in ecology and population genetics.

The code is much simpler and less error-prone.

In [26]:
np.diag(dist_africa)[:20]

array([2.6148406e-04, 3.2264848e-05, 3.7684001e-04, 5.0108111e-04,
       2.9576970e-05, 3.1618460e-05, 5.1764731e-04, 1.2238865e-04,
       1.0563929e-04, 2.0520962e-04, 2.4392410e-05, 2.7024971e-05,
       3.0752970e-05, 2.5737394e-05, 2.6121541e-05, 3.0082527e-05,
       6.3009727e-05, 6.2816712e-04, 3.4695451e-05, 2.2376076e-05],
      dtype=float32)

In [20]:
dist_africa = np.load('dist_africa.npy')